import { StyleSheet } from 'react-native';

const FOREST_GREEN = '#185C35';
const CARD_BG = '#FFFFFF';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: CARD_BG,
  },
  background: {
    position: 'absolute',
    top: 0,
    right: 0,
    left: 0,
    height: '59%',
  },
  backgroundImage: {
    width: '100%',
    height: '100%',
  },
  backgroundTint: {
    position: 'absolute',
    top: 0,
    right: 0,
    left: 0,
    height: '100%',
    backgroundColor: 'rgba(24, 92, 53, 0.08)',
  },
  backgroundLogo: {
    position: 'absolute',
    top: 70,
    alignSelf: 'center',
    width: 140,
    height: 90,
    zIndex: 1,
    elevation: 1,
    opacity: 0.96,
  },
  backgroundLogoImage: { width: '100%', height: '100%' },
  panelContainer: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 3,
    elevation: 4,
    shadowColor: FOREST_GREEN,
    shadowOffset: { width: 0, height: -6 },
    shadowOpacity: 0.16,
    shadowRadius: 18,
  },
  domeCap: {
    width: '100%',
    height: 34,
  },
  panelBody: {
    flex: 1,
    backgroundColor: CARD_BG,
    overflow: 'hidden',
    marginTop: -1,
  },
  landingContent: {
    alignItems: 'center',
    paddingTop: 14,
    paddingHorizontal: 32,
    paddingBottom: 28,
  },
  kicker: {
    color: '#3D9B43',
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0.5,
    marginBottom: 4,
    textAlign: 'center',
  },
  title: {
    color: '#22652A',
    fontSize: 24,
    fontWeight: '900',
    letterSpacing: -0.5,
    textAlign: 'center',
  },
  subtitle: {
    color: '#526157',
    fontSize: 13,
    textAlign: 'center',
    marginTop: 4,
    marginBottom: 16,
  },
  gradientButtonWrapper: {
    width: '100%',
    maxWidth: 320,
    borderRadius: 11,
    overflow: 'hidden',
    marginTop: 10,
    shadowColor: FOREST_GREEN,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.22,
    shadowRadius: 12,
    elevation: 4,
  },
  gradientButton: {
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
  },
  gradientButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  outlineButton: {
    width: '100%',
    maxWidth: 320,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 12,
    borderWidth: 1.5,
    borderColor: FOREST_GREEN,
    borderRadius: 11,
    backgroundColor: '#FFFFFF',
  },
  outlineButtonText: {
    color: FOREST_GREEN,
    fontSize: 15,
    fontWeight: '800',
    letterSpacing: -0.2,
  },
  buttonPressed: {
    opacity: 0.82,
    transform: [{ scale: 0.99 }],
  },
  orText: {
    marginTop: 12,
    marginBottom: 0,
    color: '#74806D',
    fontSize: 13,
    fontWeight: '600',
  },
  loginPrompt: {
    marginTop: 22,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  loginPromptText: { color: '#526157', fontSize: 13 },
  loginLink: { color: FOREST_GREEN, fontSize: 13, fontWeight: '800' },
  leafContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    width: 420,
    height: 280,
    zIndex: 0,
  },
  leafImage: {
    width: '100%',
    height: '100%',
    opacity: 0.95,
  },
});
