import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#ffffd8',
  },
  background: {
    position: 'absolute',
    top: 0,
    right: 0,
    left: 0,
    height: '59%',
  },
  backgroundImage: {
    width: '100%',
    height: '100%',
  },
  backgroundTint: {
    position: 'absolute',
    top: 0,
    right: 0,
    left: 0,
    height: '59%',
    backgroundColor: 'rgba(255, 226, 55, 0.28)',
  },
  backgroundLogo: {
    position: 'absolute',
    top: 82,
    alignSelf: 'center',
    width: 132,
    height: 82,
    zIndex: 1,
    elevation: 1,
    opacity: 0.96,
  },
  backgroundLogoImage: { width: '100%', height: '100%' },
  panelContainer: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 3,
    elevation: 4,
    shadowColor: '#31551e',
    shadowOffset: { width: 0, height: -6 },
    shadowOpacity: 0.16,
    shadowRadius: 18,
  },
  domeCap: {
    width: '100%',
    height: 34,
  },
  panelBody: {
    flex: 1,
    backgroundColor: '#ffffd8',
    overflow: 'hidden',
    marginTop: -1,
  },
  landingContent: {
    alignItems: 'center',
    paddingTop: 10,
    paddingHorizontal: 36,
    paddingBottom: 24,
  },
  title: {
    color: '#111315',
    fontSize: 22,
    fontWeight: '700',
    letterSpacing: -0.3,
    textAlign: 'center',
  },
  outlineButton: {
    width: '100%',
    maxWidth: 320,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 27,
    borderWidth: 1,
    borderColor: '#737373',
    borderRadius: 20,
    backgroundColor: '#ffffff',
  },
  outlineButtonText: {
    color: '#111315',
    fontSize: 17,
    fontWeight: '400',
    letterSpacing: -0.2,
  },
  buttonPressed: {
    opacity: 0.72,
    transform: [{ scale: 0.99 }],
  },
  orText: {
    marginTop: 12,
    marginBottom: -15,
    color: '#232323',
    fontSize: 15,
  },
  loginPrompt: {
    position: 'absolute',
    bottom: 19,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  loginPromptText: { color: '#5b5b54', fontSize: 16, fontWeight: '300' },
  loginLink: { color: '#638263', fontSize: 16, fontWeight: '300' },
});
