import { StyleSheet } from 'react-native';

// Web-style parts of the buyer order tracking screen (everything except the Delivery Route card,
// which keeps using buyer-order-tracking.styles.ts). Colours mirror web/src/styles/Buyer/deliveryProgress.css.
export const PAGE_BG = '#fbfaf1';
export const GREEN = '#26743a';
export const GREEN_DEEP = '#176b32';
export const TITLE_GREEN = '#197438';
export const HEADING_GREEN = '#1f7136';
export const INK = '#173b21';
export const MUTED = '#5a695d';

const cardShadow = {
  shadowColor: '#25491f',
  shadowOffset: { width: 0, height: 8 },
  shadowOpacity: 0.09,
  shadowRadius: 20,
  elevation: 3,
} as const;

export const w = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: PAGE_BG },
  scrollContent: { paddingHorizontal: 16, paddingTop: 12, paddingBottom: 40 },

  // Page title
  title: { textAlign: 'center', color: TITLE_GREEN, fontSize: 27, fontWeight: '800', letterSpacing: 0.2, lineHeight: 30, marginTop: 8, marginBottom: 20 },

  // Cards
  card: { borderRadius: 18, borderWidth: 1, borderColor: '#e4e6df', backgroundColor: '#ffffff', marginBottom: 20, ...cardShadow },
  tintCard: { borderColor: '#dce7d7', backgroundColor: '#fffef8', paddingVertical: 22, paddingHorizontal: 18 },
  cardHeading: {
    color: HEADING_GREEN,
    fontSize: 20,
    fontWeight: '700',
    borderBottomWidth: 1,
    borderBottomColor: '#cdddc8',
    paddingBottom: 13,
  },

  // Order Details rows
  detailList: { marginTop: 22 },
  detailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    minHeight: 72,
    marginTop: 14,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e1eadc',
    backgroundColor: '#f4f8ef',
    shadowColor: '#193a19',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.07,
    shadowRadius: 12,
    elevation: 1,
  },
  detailRowFirst: { marginTop: 0 },
  badge: { width: 46, height: 46, borderRadius: 23, alignItems: 'center', justifyContent: 'center' },
  detailText: { flex: 1, minWidth: 0 },
  detailLabel: { color: GREEN_DEEP, fontSize: 14, fontWeight: '800' },
  detailValue: { marginTop: 3, color: '#3d894a', fontSize: 11.5, lineHeight: 16 },

  // Proof of delivery (inside Order Details)
  proof: { marginTop: 18, paddingTop: 16, borderTopWidth: 1, borderTopColor: '#e1eadc' },
  proofLabelRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 10 },
  proofLabel: { color: GREEN, fontSize: 12.5, fontWeight: '800' },
  proofPhoto: { height: 170, borderRadius: 12, borderWidth: 1, borderColor: '#dce7dc', backgroundColor: '#f0f4ef', overflow: 'hidden' },
  proofImage: { width: '100%', height: '100%' },
  proofZoom: {
    position: 'absolute',
    right: 8,
    bottom: 8,
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.92)',
  },
  proofNote: { marginTop: 8, color: '#4c5b4e', fontSize: 12, lineHeight: 18 },
  proofNoteBold: { color: INK, fontWeight: '700' },
  lightbox: { flex: 1, backgroundColor: 'rgba(10,26,15,0.92)', justifyContent: 'center' },
  lightboxImage: { width: '100%', height: '70%' },
  lightboxClose: { position: 'absolute', top: 48, right: 20, width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,255,255,0.16)' },
  lightboxCaption: { paddingHorizontal: 20, paddingTop: 14, color: '#ffffff', fontSize: 12 },

  // Order Items
  itemList: { marginTop: 20 },
  item: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    paddingTop: 8,
    paddingBottom: 13,
    paddingHorizontal: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#c8d9c3',
    borderRadius: 10,
    backgroundColor: '#fbfcf4',
  },
  itemImage: { width: 62, height: 78, resizeMode: 'contain' },
  itemName: { color: GREEN_DEEP, fontSize: 13, fontWeight: '800' },
  itemMeta: { marginTop: 5, color: '#397c45', fontSize: 11 },
  itemPrice: { marginTop: 4, color: '#24803a', fontSize: 13, fontWeight: '700' },
  costRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 18, paddingTop: 14, paddingHorizontal: 10, borderTopWidth: 1, borderTopColor: '#d7e3d2' },
  costLabel: { color: '#285f35', fontSize: 13 },
  costValue: { color: GREEN_DEEP, fontSize: 13, fontWeight: '800' },
  totalBar: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 20, paddingVertical: 13, paddingHorizontal: 18, borderRadius: 12, backgroundColor: '#c8dfad' },
  totalLabel: { color: '#1d6733', fontSize: 16, fontWeight: '800' },
  totalValue: { color: '#1d6733', fontSize: 19, fontWeight: '800' },

  // Action cards (cancel / receipt)
  actionCard: { paddingVertical: 20, paddingHorizontal: 22 },
  actionTitle: { color: HEADING_GREEN, fontSize: 16, fontWeight: '700' },
  actionText: { marginTop: 10, color: '#4c5b4e', fontSize: 12, lineHeight: 18 },
  actionErrorText: { marginTop: 10, color: '#a42626', fontSize: 12 },
  actionButtons: { gap: 10, marginTop: 14 },
  button: { minHeight: 44, borderRadius: 9, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 20 },
  buttonText: { fontSize: 12.5, fontWeight: '800' },
  buttonPrimary: { backgroundColor: GREEN },
  buttonPrimaryText: { color: '#ffffff' },
  buttonSecondary: { backgroundColor: '#eaf2e6' },
  buttonSecondaryText: { color: '#2c5330' },
  buttonDanger: { backgroundColor: '#b13b3b' },
  buttonDangerText: { color: '#ffffff' },
  buttonDisabled: { opacity: 0.6 },

  // Rating card
  rateCard: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', justifyContent: 'space-between', gap: 16, paddingVertical: 20, paddingHorizontal: 22 },
  rateText: { flexShrink: 1, minWidth: 180 },
  rateTitle: { color: HEADING_GREEN, fontSize: 17, fontWeight: '700' },
  rateCopy: { marginTop: 4, color: MUTED, fontSize: 12, lineHeight: 18 },
  stars: { flexDirection: 'row', gap: 2 },
  star: { fontSize: 30, lineHeight: 34, color: '#c7cdc6', paddingHorizontal: 1 },
  starFilled: { color: '#e9a528' },
  reportNote: { textAlign: 'center', color: MUTED, fontSize: 12.5, fontWeight: '700', textDecorationLine: 'underline', paddingVertical: 8 },

  // Pickup ticket
  ticket: { paddingVertical: 20, paddingHorizontal: 22, borderWidth: 1.5, borderStyle: 'dashed', borderColor: '#f0dba8', backgroundColor: '#fffaf0' },
  ticketLabel: { color: '#9a710e', fontSize: 10, fontWeight: '800', letterSpacing: 1, textTransform: 'uppercase' },
  ticketCode: { marginTop: 4, color: INK, fontSize: 22, fontWeight: '800', letterSpacing: 1 },
  ticketCopy: { marginTop: 8, color: MUTED, fontSize: 12.5, lineHeight: 19 },
  ticketMeta: { gap: 12, marginTop: 18, paddingTop: 16, borderTopWidth: 1, borderStyle: 'dashed', borderTopColor: '#f0dba8' },
  ticketMetaRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 10 },
  ticketMetaTitle: { color: INK, fontSize: 12.5, fontWeight: '800' },
  ticketMetaSub: { marginTop: 1, color: MUTED, fontSize: 11.5 },
  ticketButton: { flexDirection: 'row', alignItems: 'center', alignSelf: 'flex-start', gap: 7, marginTop: 16, borderRadius: 9, paddingVertical: 10, paddingHorizontal: 18, backgroundColor: GREEN },
  ticketButtonText: { color: '#ffffff', fontSize: 12.5, fontWeight: '800' },

  // Return card
  returnCard: { padding: 16, borderRadius: 16, borderWidth: 1, borderColor: '#e2e8df', backgroundColor: '#ffffff', marginBottom: 20, ...cardShadow, shadowOpacity: 0.06 },
  returnTopRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  pill: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingVertical: 4, paddingHorizontal: 11, borderRadius: 999 },
  pillDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: '#9a710e' },
  pillText: { fontSize: 12, fontWeight: '800' },
  pillReview: { backgroundColor: '#fdf3df' },
  pillReviewText: { color: '#9a710e' },
  pillApproved: { backgroundColor: '#e6f4ea' },
  pillApprovedText: { color: '#176b32' },
  pillDismissed: { backgroundColor: '#fdecea' },
  pillDismissedText: { color: '#8c1d18' },
  returnView: { flexDirection: 'row', alignItems: 'center' },
  returnViewText: { color: '#1f7438', fontSize: 13, fontWeight: '800' },
  returnTitle: { marginTop: 12, color: INK, fontSize: 18, fontWeight: '800', lineHeight: 23 },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 10, marginBottom: 18 },
  chip: { paddingVertical: 3, paddingHorizontal: 10, borderRadius: 999, backgroundColor: '#f1f4ee' },
  chipText: { color: '#4c5b4e', fontSize: 12, fontWeight: '600' },
  returnFooter: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 16, paddingTop: 12, borderTopWidth: 1, borderTopColor: '#eaefe8' },
  footerText: { flexShrink: 1, color: MUTED, fontSize: 12, lineHeight: 17 },
  footerAmount: { color: INK, fontSize: 13, fontWeight: '800', marginBottom: 2 },

  // Progress stepper (return card)
  stepper: { flexDirection: 'row' },
  stepCol: { flex: 1, alignItems: 'center', paddingHorizontal: 2 },
  stepLine: { position: 'absolute', top: 17, right: '50%', width: '100%', height: 2, backgroundColor: '#d5ddd2' },
  stepLineOn: { backgroundColor: '#27823f' },
  stepRing: { width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center', marginBottom: 6 },
  stepRingCurrent: { backgroundColor: 'rgba(51,139,63,0.14)' },
  stepNode: { width: 28, height: 28, borderRadius: 14, borderWidth: 1.5, borderColor: '#d5ddd2', backgroundColor: '#ffffff', alignItems: 'center', justifyContent: 'center' },
  stepNodeDone: { borderColor: '#27823f', backgroundColor: '#27823f' },
  stepNodeCurrent: { borderColor: '#27823f' },
  stepNodeDeclined: { borderColor: '#b3261e', backgroundColor: '#b3261e' },
  stepLabel: { color: '#8a968b', fontSize: 12, fontWeight: '700', textAlign: 'center', lineHeight: 15 },
  stepLabelOn: { color: INK },
  stepSub: { marginTop: 2, color: '#68736b', fontSize: 11, fontWeight: '600', textAlign: 'center' },

  // Cancelled receipt page
  receiptCard: { paddingVertical: 24, paddingHorizontal: 20, alignItems: 'center' },
  receiptHero: { width: 52, height: 52, borderRadius: 26, alignItems: 'center', justifyContent: 'center', backgroundColor: '#fbeaea', marginBottom: 10 },
  receiptTitle: { color: '#25783b', fontSize: 20, fontWeight: '700' },
  receiptWhen: { marginTop: 4, marginBottom: 16, color: '#68736b', fontSize: 12, textAlign: 'center' },
  facts: { alignSelf: 'stretch' },
  fact: { flexDirection: 'row', justifyContent: 'space-between', gap: 16, paddingVertical: 10, borderTopWidth: 1, borderTopColor: '#edf1eb' },
  factLabel: { color: '#68736b', fontSize: 12.5 },
  factValue: { flex: 1, color: INK, fontSize: 12.5, fontWeight: '700', textAlign: 'right' },
  refundNote: { alignSelf: 'stretch', marginTop: 10, color: MUTED, fontSize: 12, lineHeight: 18 },
  itemsHeading: { color: '#25783b', fontSize: 17, fontWeight: '700' },
  tableHead: { flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: 12, paddingBottom: 8, borderBottomWidth: 1, borderBottomColor: '#edf1eb' },
  tableRow: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 9, borderBottomWidth: 1, borderBottomColor: '#edf1eb' },
  colThumb: { width: 44 },
  colItem: { flex: 1, minWidth: 0 },
  colQty: { width: 40, textAlign: 'right' },
  colPrice: { width: 78, textAlign: 'right' },
  tableHeadText: { color: '#8a968b', fontSize: 11 },
  tableThumb: { width: 44, height: 44, resizeMode: 'contain' },
  tableName: { color: '#5a695d', fontSize: 12.5, fontWeight: '700' },
  tableMeta: { marginTop: 2, color: '#8a968b', fontSize: 11 },
  tableCell: { color: '#6f7d72', fontSize: 12.5 },
  sumRow: { flexDirection: 'row', justifyContent: 'space-between', paddingTop: 8 },
  sumText: { color: '#5a695d', fontSize: 12.5 },
  sumTotal: { marginTop: 6, paddingTop: 12, borderTopWidth: 1, borderTopColor: '#edf1eb' },
  sumTotalText: { color: INK, fontSize: 14, fontWeight: '800' },
  bigButtons: { alignItems: 'center', gap: 14, paddingTop: 6 },
  bigButton: { alignSelf: 'stretch', minHeight: 58, borderRadius: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10, paddingHorizontal: 28 },
  bigButtonOutline: { borderWidth: 1, borderColor: GREEN, backgroundColor: '#ffffff' },
  bigButtonFilled: { backgroundColor: GREEN },
  bigButtonText: { fontSize: 16, fontWeight: '800' },
  bigButtonOutlineText: { color: GREEN },
  bigButtonFilledText: { color: '#ffffff' },
  backToCancellation: { flexDirection: 'row', alignItems: 'center', alignSelf: 'flex-start', gap: 6, paddingVertical: 8, paddingHorizontal: 16, marginBottom: 16, borderRadius: 10, borderWidth: 1, borderColor: GREEN, backgroundColor: '#ffffff' },
  backToCancellationText: { color: GREEN, fontSize: 13, fontWeight: '800' },
});
