import { StyleSheet } from 'react-native';

const DARK_GREEN = '#10351D';
const GREEN = '#176D34';
const TEXT_MUTED = '#637567';
const CARD_BORDER = '#E3EBE4';
const DANGER = '#B23A32';

export const styles = StyleSheet.create({
  modalBackdrop: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(9, 32, 16, 0.55)',
  },
  modalCard: {
    maxHeight: '90%',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    backgroundColor: '#ffffff',
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 28,
    borderWidth: 1,
    borderColor: CARD_BORDER,
  },
  modalHandleBar: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#D6DFD4',
    alignSelf: 'center',
    marginBottom: 14,
  },
  modalHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  modalTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: DARK_GREEN,
    letterSpacing: -0.2,
  },
  modalCloseButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#F2F6F0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalSubtitle: {
    fontSize: 12.5,
    color: TEXT_MUTED,
    lineHeight: 18,
    marginBottom: 16,
  },
  orderSummary: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    backgroundColor: '#F4F2E6',
    borderWidth: 1,
    borderColor: CARD_BORDER,
    borderRadius: 12,
    paddingHorizontal: 13,
    paddingVertical: 11,
    marginBottom: 16,
  },
  orderSummaryNumber: { fontSize: 12.5, fontWeight: '800', color: DARK_GREEN },
  orderSummaryItems: { fontSize: 11, color: TEXT_MUTED, marginTop: 2 },
  orderSummaryTotal: { fontSize: 13.5, fontWeight: '800', color: GREEN },
  reasonsLabel: { fontSize: 11.5, fontWeight: '800', color: DARK_GREEN, marginBottom: 6 },
  reasonRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 9,
  },
  reasonText: { fontSize: 13, color: '#223924', flexShrink: 1 },
  radioOuter: {
    width: 19,
    height: 19,
    borderRadius: 10,
    borderWidth: 1.6,
    borderColor: '#C3D0C1',
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioOuterSelected: { borderColor: DANGER },
  radioInner: { width: 9, height: 9, borderRadius: 5, backgroundColor: DANGER },
  noteInput: {
    marginTop: 4,
    marginBottom: 4,
    minHeight: 64,
    borderWidth: 1,
    borderColor: CARD_BORDER,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 12.5,
    color: DARK_GREEN,
    textAlignVertical: 'top',
  },
  refundNote: {
    backgroundColor: '#FDF3DF',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginTop: 12,
  },
  refundNoteText: { fontSize: 11.5, fontWeight: '600', color: '#9A710E', lineHeight: 16 },
  errorText: { fontSize: 11.5, color: '#a33d35', marginTop: 12 },
  modalActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 18,
  },
  keepButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 13,
    borderRadius: 24,
    borderWidth: 1.5,
    borderColor: CARD_BORDER,
    backgroundColor: '#FAFCF9',
  },
  keepButtonText: { fontSize: 13, fontWeight: '800', color: '#556658' },
  confirmButton: {
    flex: 1.2,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 13,
    borderRadius: 24,
    backgroundColor: DANGER,
  },
  confirmButtonText: { fontSize: 13, fontWeight: '800', color: '#ffffff' },
  buttonDisabled: { opacity: 0.55 },
});
