import { StyleSheet } from 'react-native';

export const GREEN = '#176D34';
export const DARK_GREEN = '#10351D';
export const SAGE_BG = '#EDF5EB';
export const SAGE_BORDER = '#D8E5D5';
export const CARD_BORDER = '#E5EDE2';
export const TEXT_MUTED = '#637567';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: GREEN,
  },
  mainBodyContainer: {
    flex: 1,
    backgroundColor: '#F3F7F1',
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 18,
    paddingBottom: 28,
  },

    titleText: {
    fontSize: 20,
    fontWeight: '800',
    color: DARK_GREEN,
    textAlign: 'center',
    marginBottom: 16,
    letterSpacing: -0.3,
  },

  // Hero profile card
  profileHeroCard: {
    padding: 16,
    borderRadius: 20,
    backgroundColor: '#ffffff',
    marginBottom: 14,
    borderWidth: 1,
    borderColor: CARD_BORDER,
    position: 'relative',
    shadowColor: '#0B2E16',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  pencilButton: {
    position: 'absolute',
    top: 12,
    right: 12,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#F3F8F4',
    borderWidth: 1,
    borderColor: '#CDE5CF',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 5,
  },
  pencilButtonPressed: {
    backgroundColor: '#E2EFE4',
    transform: [{ scale: 0.94 }],
  },
  heroIdentity: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    paddingRight: 36,
  },
  avatarWrap: {
    position: 'relative',
    alignSelf: 'center',
  },
  initialsCircle: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: GREEN,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#E8F5E9',
    shadowColor: GREEN,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 3,
  },
  initialsText: {
    fontSize: 21,
    fontWeight: '900',
    color: '#ffffff',
    letterSpacing: 0.5,
  },
  avatarBadge: {
    position: 'absolute',
    right: -2,
    bottom: -2,
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#176D34',
    borderWidth: 2,
    borderColor: '#ffffff',
  },
  heroDetails: {
    flex: 1,
    minWidth: 0,
  },
  heroName: {
    fontSize: 16,
    fontWeight: '800',
    color: DARK_GREEN,
  },
  heroEmail: {
    fontSize: 11.5,
    color: TEXT_MUTED,
    marginTop: 2,
  },
  heroBadgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 6,
  },
  verifiedChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EDF6EE',
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#CBE5D0',
    gap: 3,
  },
  verifiedChipText: {
    fontSize: 9.5,
    fontWeight: '700',
    color: GREEN,
  },
  memberSinceText: {
    fontSize: 10,
    color: '#8E9E91',
    fontWeight: '500',
  },

  // Edit form card
  editFormCard: {
    padding: 16,
    borderRadius: 20,
    backgroundColor: '#ffffff',
    marginBottom: 14,
    borderWidth: 1.5,
    borderColor: '#CDE5CF',
    shadowColor: '#0B2E16',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  editFormHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#EDF2EC',
    marginBottom: 8,
  },
  editFormTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  editFormDot: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
    backgroundColor: GREEN,
  },
  editFormTitle: {
    fontSize: 12.5,
    fontWeight: '800',
    color: DARK_GREEN,
  },
  fieldLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#475C4D',
    marginBottom: 4,
    marginTop: 8,
  },
  fieldInput: {
    backgroundColor: '#F8FAF7',
    borderWidth: 1,
    borderColor: '#DCE7DE',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 9,
    fontSize: 12.5,
    color: '#1B3121',
  },
  fieldInputMultiline: {
    minHeight: 52,
    textAlignVertical: 'top',
  },
  formButtonsRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 14,
  },
  cancelFormButton: {
    flex: 1,
    paddingVertical: 11,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#CFD9D1',
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelFormButtonText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#556658',
  },
  saveFormButton: {
    flex: 1,
    paddingVertical: 11,
    borderRadius: 12,
    backgroundColor: GREEN,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: GREEN,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  saveFormButtonText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#ffffff',
  },

  // Account details card
  detailsCard: {
    padding: 16,
    borderRadius: 20,
    backgroundColor: '#ffffff',
    marginBottom: 14,
    borderWidth: 1,
    borderColor: CARD_BORDER,
    shadowColor: '#0B2E16',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 1,
  },
  detailsSectionTitle: {
    fontSize: 12.5,
    fontWeight: '800',
    color: DARK_GREEN,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#EDF2EC',
    marginBottom: 6,
  },
  detailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 7,
  },
  detailIconBox: {
    width: 34,
    height: 34,
    borderRadius: 9,
    backgroundColor: '#F4F8F4',
    borderWidth: 1,
    borderColor: '#E3ECE4',
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailTextBlock: {
    flex: 1,
  },
  detailLabel: {
    fontSize: 9.5,
    fontWeight: '700',
    color: '#8A9C8E',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  detailValue: {
    fontSize: 12.5,
    fontWeight: '600',
    color: '#2C3E30',
    marginTop: 1,
  },

  purchasesCard: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 14,
    borderRadius: 18,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: CARD_BORDER,
    marginBottom: 14,
    shadowColor: '#0B2E16',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 1,
  },
  purchasesPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.99 }],
  },
  purchasesIconCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: SAGE_BG,
    borderWidth: 1,
    borderColor: SAGE_BORDER,
  },
  purchasesTextBlock: {
    flex: 1,
    marginLeft: 12,
  },
  purchasesTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: DARK_GREEN,
  },
  purchasesSubtitle: {
    fontSize: 10.5,
    color: TEXT_MUTED,
    marginTop: 1.5,
  },

  // Sign out button
  signOutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 13,
    borderRadius: 14,
    backgroundColor: '#FDF2F0',
    borderWidth: 1,
    borderColor: '#F5D3CE',
    marginTop: 6,
    marginBottom: 8,
  },
  signOutButtonPressed: {
    backgroundColor: '#FBE8E5',
    transform: [{ scale: 0.98 }],
  },
  signOutButtonText: {
    fontSize: 12.5,
    fontWeight: '800',
    color: '#B4463A',
    letterSpacing: 0.3,
  },
  buttonDisabled: {
    opacity: 0.65,
  },
});
