import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#eef6df' },
  container: { flex: 1, justifyContent: 'center', paddingHorizontal: 24 },
  scrollContainer: { flexGrow: 1, justifyContent: 'center', padding: 24 },
  card: {
    backgroundColor: '#fff',
    borderRadius: 22,
    padding: 24,
    shadowColor: '#173d20',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 18,
    elevation: 5,
  },
  title: { color: '#174e2b', fontSize: 27, fontWeight: '800' },
  subtitle: { color: '#657269', fontSize: 14, lineHeight: 20, marginTop: 5, marginBottom: 18 },
  label: { color: '#1d3424', fontSize: 13, fontWeight: '700', marginBottom: 7, marginTop: 10 },
  input: {
    height: 50,
    borderWidth: 1,
    borderColor: '#cddbc7',
    backgroundColor: '#fbfcf8',
    borderRadius: 12,
    paddingHorizontal: 15,
    color: '#101a13',
    fontSize: 15,
  },
  readOnly: { backgroundColor: '#edf2ea', color: '#526057' },
  category: { color: '#176c35', fontSize: 14, fontWeight: '800', marginBottom: 8 },
  requirements: { color: '#657269', fontSize: 13, lineHeight: 20, marginTop: 12 },
  error: { color: '#bb2828', fontSize: 13, marginTop: 13, lineHeight: 18 },
  button: {
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#18753a',
    borderRadius: 13,
    marginTop: 22,
  },
  buttonText: { color: '#fff', fontSize: 16, fontWeight: '800' },
  signOut: { alignItems: 'center', marginTop: 16, padding: 8 },
  signOutText: { color: '#18753a', fontSize: 14, fontWeight: '700' },
});
