import { StyleSheet } from 'react-native';

const GREEN = '#176b32';

export const styles = StyleSheet.create({
  flex: { flex: 1 },
  safeArea: { flex: 1, backgroundColor: 'transparent' },
  blurBackdrop: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0 },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: '#d9d9d9' },
  page: { flexGrow: 1, justifyContent: 'center', paddingVertical: 34 },
  formCard: {
    width: '100%',
    maxWidth: 520,
    alignSelf: 'center',
    backgroundColor: '#fff',
    borderRadius: 8,
    overflow: 'hidden',
  },
  categoryHeader: { height: 59, backgroundColor: '#2f7f2d', flexDirection: 'row', alignItems: 'center', paddingHorizontal: 17 },
  categoryIcon: { width: 45, height: 45, borderRadius: 23, backgroundColor: '#fff', alignItems: 'center', justifyContent: 'center', overflow: 'hidden' },
  categoryImage: { width: 40, height: 38, resizeMode: 'contain' },
  categoryTitle: { color: '#fff', fontSize: 19, fontWeight: '800', marginLeft: 14 },
  categorySubtitle: { color: '#e3f0df', fontSize: 11, fontWeight: '700', marginLeft: 14, marginTop: 2 },
  formBody: { paddingHorizontal: 11, paddingTop: 10, paddingBottom: 30 },
  confirmationText: { color: '#516054', fontSize: 12, lineHeight: 18, paddingHorizontal: 18, paddingVertical: 14 },
  fieldGroup: { borderWidth: 1, borderColor: '#ededed', minHeight: 68, paddingHorizontal: 28, paddingTop: 9, marginBottom: 8 },
  label: { color: '#176b32', fontSize: 10, lineHeight: 14, fontWeight: '700' },
  readonlyStrong: { color: '#111', fontSize: 16, fontWeight: '700', marginTop: 10, marginLeft: 7 },
  timeRow: { height: 38, flexDirection: 'row', alignItems: 'center', marginTop: 1 },
  clock: { width: 21, height: 21, borderRadius: 11, borderWidth: 1.5, borderColor: '#69807a', marginHorizontal: 7 },
  clockHour: { position: 'absolute', width: 1.5, height: 6, backgroundColor: '#69807a', top: 4, left: 9 },
  clockMinute: { position: 'absolute', width: 6, height: 1.5, backgroundColor: '#69807a', top: 10, left: 9, transform: [{ rotate: '30deg' }] },
  timeInput: { width: '54%', minWidth: 160, height: 34, borderWidth: 1, borderColor: '#ededed', color: '#111', fontSize: 15, fontWeight: '700', paddingHorizontal: 22, paddingVertical: 3 },
  chevron: { color: '#18703a', fontSize: 22, marginLeft: -27, marginTop: -4 },
  descriptionGroup: { minHeight: 105 },
  description: { color: '#111', fontSize: 15, lineHeight: 21, fontWeight: '700', marginTop: 22, marginLeft: 18 },
  insightsGroup: { minHeight: 166, paddingBottom: 8 },
  insightsInput: { flex: 1, minHeight: 127, marginTop: 8, borderWidth: 1, borderColor: '#ededed', color: '#171717', fontSize: 14, padding: 8 },
  errorText: { color: '#aa322d', fontSize: 11, lineHeight: 16, marginHorizontal: 4, marginBottom: 8 },
  submitButton: { minWidth: 132, height: 31, paddingHorizontal: 20, borderRadius: 4, backgroundColor: '#21783a', alignSelf: 'center', alignItems: 'center', justifyContent: 'center', marginTop: 18, elevation: 5, shadowColor: '#555', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 5 },
  submitButtonPressed: { opacity: 0.7 },
  submitText: { color: '#fff', fontSize: 9, fontWeight: '800' },
  actions: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 10, marginTop: 4 },
  cancelButton: { minWidth: 100, height: 31, paddingHorizontal: 20, borderRadius: 4, borderWidth: 1, borderColor: '#aeb8af', alignItems: 'center', justifyContent: 'center', marginTop: 18 },
  cancelText: { color: GREEN, fontSize: 9, fontWeight: '800' },
  loadingCard: { alignItems: 'center', gap: 10, backgroundColor: '#fff', padding: 40, borderRadius: 8 },
  loadingText: { color: '#617064', fontSize: 12 },
  errorCard: { backgroundColor: '#fff', borderRadius: 8, padding: 24, alignItems: 'center' },
  backText: { color: GREEN, fontSize: 12, fontWeight: '800', marginTop: 10 },
});
