import { StyleSheet } from 'react-native';

const COLORS = {
  background: '#fbfbf3',
  green: '#216c36',
  deepGreen: '#176b32',
  white: '#ffffff',
};

const cardShadow = {
  elevation: 4,
  shadowColor: '#586353',
  shadowOffset: { width: 0, height: 4 },
  shadowOpacity: 0.2,
  shadowRadius: 6,
};

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#e5e5e5', alignItems: 'center' },
  page: {
    flex: 1,
    width: '100%',
    backgroundColor: COLORS.background,
    overflow: 'hidden',
  },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: COLORS.background },
  scrollContent: { paddingTop: 28, paddingBottom: 34 },
  welcomeRow: { height: 184, flexDirection: 'row', position: 'relative', overflow: 'hidden' },
  greeting: { width: '41%', color: COLORS.green, fontSize: 38, lineHeight: 55, fontWeight: '800', letterSpacing: 0.1, zIndex: 2, paddingTop: 4 },
  heroArt: { position: 'absolute', width: '80%', height: 180, right: -8, bottom: 0, resizeMode: 'cover' },
  weatherCard: { height: 185, borderRadius: 8, overflow: 'hidden', flexDirection: 'row', alignItems: 'center', paddingHorizontal: 19, marginBottom: 26 },
  weatherImage: { borderRadius: 8, resizeMode: 'cover' },
  weatherShade: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0, backgroundColor: 'rgba(24, 43, 35, 0.22)' },
  weatherCopy: { flex: 1, alignSelf: 'stretch', paddingTop: 20, zIndex: 1 },
  todayLabel: { color: COLORS.white, fontWeight: '800', fontSize: 20 },
  weatherTitle: { color: COLORS.white, fontWeight: '800', fontSize: 41, lineHeight: 47 },
  location: { color: COLORS.white, fontSize: 14 },
  wind: { color: COLORS.white, fontSize: 11, fontWeight: '700', marginTop: 13 },
  forecastColumn: { width: '20%', minWidth: 76, alignItems: 'center', zIndex: 1 },
  forecastDate: { color: COLORS.white, fontSize: 13, fontWeight: '800', marginBottom: 12 },
  forecastTile: { width: 72, height: 77, borderRadius: 7, backgroundColor: 'rgba(238, 241, 237, 0.63)', alignItems: 'center', justifyContent: 'center' },
  weatherIcon: { width: 58, height: 54, position: 'relative' },
  sun: { position: 'absolute', width: 23, height: 23, borderRadius: 12, backgroundColor: '#ffd400', right: 5, top: 5 },
  sunRay: { position: 'absolute', width: 4, height: 9, borderRadius: 3, backgroundColor: '#ffd400' },
  sunRayTop: { right: 14, top: -3 },
  sunRayLeft: { right: 34, top: 11, transform: [{ rotate: '-55deg' }] },
  sunRayRight: { right: -1, top: 11, transform: [{ rotate: '55deg' }] },
  cloudBack: { position: 'absolute', width: 31, height: 29, borderRadius: 18, backgroundColor: '#d3e4f3', left: 10, bottom: 7 },
  cloudFront: { position: 'absolute', width: 49, height: 19, borderRadius: 14, backgroundColor: '#d3e4f3', left: 2, bottom: 3 },
  metricsRow: { flexDirection: 'row', gap: 18, marginHorizontal: 4, marginBottom: 34 },
  metricCard: { flex: 1, height: 94, borderRadius: 8, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 4, ...cardShadow },
  metricValue: { color: COLORS.deepGreen, fontSize: 27, lineHeight: 34, fontWeight: '700', marginBottom: 6 },
  metricLabel: { color: COLORS.white, fontSize: 11, textAlign: 'center', width: '100%' },
  equipmentTitle: { color: COLORS.green, fontSize: 29, fontWeight: '800', marginLeft: 16, marginBottom: 20 },
  equipmentRow: { flexDirection: 'row', gap: 18, marginHorizontal: 31, marginBottom: 35 },
  equipmentCard: { flex: 1, aspectRatio: 1.25, borderRadius: 8, alignItems: 'center', justifyContent: 'flex-end', paddingBottom: 9, overflow: 'hidden', ...cardShadow },
  equipmentVehicle: { position: 'absolute', width: '96%', height: '78%', top: 3, resizeMode: 'contain' },
  equipmentLabel: { color: COLORS.white, fontSize: 9, fontWeight: '700' },
  sectionHeading: { flexDirection: 'row', alignItems: 'center', gap: 14, marginLeft: 30, marginBottom: 20 },
  sectionTitle: { color: COLORS.green, fontSize: 28, fontWeight: '800' },
  clipboard: { width: 29, height: 36, borderColor: '#287d43', borderWidth: 2.5, borderRadius: 2, position: 'relative' },
  clipboardClip: { position: 'absolute', top: -6, left: 7, width: 12, height: 7, borderRadius: 2, borderWidth: 2.5, borderColor: '#287d43', backgroundColor: COLORS.background },
  clipboardLine: { position: 'absolute', left: 3, right: 3, height: 7, flexDirection: 'row', alignItems: 'center' },
  clipboardCheck: { color: '#287d43', fontSize: 9, fontWeight: '900', width: 10 },
  clipboardRule: { height: 2, borderRadius: 2, backgroundColor: '#287d43', flex: 1 },
  loader: { marginVertical: 25 },
  loadError: { color: '#a33d35', fontSize: 12, textAlign: 'center', marginBottom: 14 },
  taskCard: { height: 63, borderRadius: 8, backgroundColor: COLORS.white, flexDirection: 'row', alignItems: 'center', paddingRight: 22, marginBottom: 18, borderWidth: 1, borderColor: '#d8dadd', ...cardShadow },
  taskThumbnail: { width: 60, height: 53, marginLeft: 1, marginRight: 20, backgroundColor: '#f0f2f0', alignItems: 'center', justifyContent: 'center' },
  taskVehicle: { width: 49, height: 44, resizeMode: 'contain' },
  taskCopy: { flex: 1 },
  taskCategory: { color: COLORS.deepGreen, fontSize: 10, fontWeight: '700', marginBottom: 7 },
  taskDescription: { color: '#252525', fontSize: 16 },
  statusDot: { width: 13, height: 13, borderRadius: 7, backgroundColor: '#247842' },
});
