import { StyleSheet } from 'react-native';

const shadow = {
  elevation: 5,
  shadowColor: '#66705f',
  shadowOffset: { width: 0, height: 5 },
  shadowOpacity: 0.2,
  shadowRadius: 8,
};

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#fbfbf3' },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: '#fbfbf3' },
  content: { flexGrow: 1, paddingTop: 43, paddingBottom: 110 },
  titleRow: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', paddingHorizontal: 7 },
  sectionTitle: { color: '#216c36', fontSize: 29, lineHeight: 37, fontWeight: '800', letterSpacing: 0.1 },
  signOut: { color: '#247637', fontSize: 11, fontWeight: '800', paddingVertical: 9 },
  filters: { flexDirection: 'row', gap: 8, marginHorizontal: 5, marginTop: 25, marginBottom: 27 },
  filterButton: {
    flex: 1,
    height: 27,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 15,
    borderWidth: 1,
    borderColor: '#d9dcdf',
    ...shadow,
  },
  filterButtonActive: { backgroundColor: '#207a3d', borderColor: '#207a3d' },
  filterText: { color: '#26713d', fontSize: 10, fontWeight: '700' },
  completedFilterText: { color: '#1d1d1d' },
  filterTextActive: { color: '#fff' },
  taskCard: {
    backgroundColor: '#fff',
    borderRadius: 8,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#d8dbde',
    overflow: 'hidden',
    ...shadow,
  },
  taskCardExpanded: {
    backgroundColor: '#eaf3d9',
    borderColor: '#eaf3d9',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 25,
    shadowOpacity: 0,
    elevation: 0,
  },
  taskSummary: { minHeight: 61, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 10 },
  taskIconCircle: { width: 55, height: 50, backgroundColor: '#f0f2ef', alignItems: 'center', justifyContent: 'center' },
  taskIcon: { width: 48, height: 45, resizeMode: 'contain' },
  taskTitleArea: { flex: 1, minWidth: 0, paddingHorizontal: 14 },
  taskCategory: { color: '#176b32', fontSize: 10, fontWeight: '700', marginBottom: 6 },
  taskDescription: { color: '#202020', fontSize: 17, lineHeight: 22 },
  priority: {
    width: 72,
    height: 27,
    borderRadius: 15,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#d8dadd',
    alignItems: 'center',
    justifyContent: 'center',
    ...shadow,
  },
  priority_high: { backgroundColor: '#fff' },
  priority_medium: { backgroundColor: '#fff' },
  priority_low: { backgroundColor: '#fff' },
  priorityText: { color: '#25713c', fontSize: 10, fontWeight: '700', textTransform: 'capitalize' },
  details: {
    backgroundColor: '#fff',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#d5d8dc',
    paddingHorizontal: 17,
    paddingTop: 15,
    paddingBottom: 20,
  },
  detailBox: {
    minHeight: 72,
    justifyContent: 'center',
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#e4e6e8',
    paddingHorizontal: 33,
    paddingVertical: 11,
    marginBottom: 12,
    borderRadius: 9,
  },
  detailLabel: { color: '#176b32', fontSize: 10, lineHeight: 13, fontWeight: '700', marginBottom: 12 },
  detailValue: { color: '#202020', fontSize: 17, lineHeight: 22 },
  vehicleField: { minHeight: 88, paddingHorizontal: 25, paddingTop: 10, paddingBottom: 12 },
  vehicleSelect: {
    width: '57%',
    minWidth: 180,
    height: 41,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e3e5e7',
    paddingHorizontal: 13,
  },
  vehicleValue: { flex: 1, color: '#202020', fontSize: 14 },
  chevron: {
    width: 13,
    height: 13,
    borderRightWidth: 2,
    borderBottomWidth: 2,
    borderColor: '#1d7138',
    transform: [{ rotate: '45deg' }, { translateY: -3 }],
  },
  startButton: {
    height: 31,
    minWidth: 143,
    paddingHorizontal: 22,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#237b3d',
    borderRadius: 5,
    marginTop: -6,
    ...shadow,
  },
  startButtonText: { color: '#fff', fontSize: 10, fontWeight: '700' },
  buttonPressed: { opacity: 0.75 },
  completedBanner: { alignSelf: 'center', backgroundColor: '#dcefd5', borderRadius: 12, paddingHorizontal: 16, paddingVertical: 7 },
  completedText: { color: '#23733a', fontSize: 11, fontWeight: '800' },
  completedIcon: { width: 18, height: 18, borderRadius: 10, backgroundColor: '#68c20c', alignItems: 'center', justifyContent: 'center' },
  completedCheck: { color: '#fff', fontSize: 13, lineHeight: 16, fontWeight: '900' },
  errorBox: { backgroundColor: '#fff0ef', borderRadius: 10, padding: 12, marginBottom: 12, borderWidth: 1, borderColor: '#f0ceca' },
  errorText: { color: '#ad2d2d', fontSize: 12, lineHeight: 17 },
  loader: { marginTop: 50 },
  retry: { color: '#7b2727', fontSize: 11, fontWeight: '800', marginTop: 4 },
  loadingBox: { alignItems: 'center', justifyContent: 'center', paddingVertical: 56, gap: 10 },
  loadingText: { color: '#6a796c', fontSize: 12 },
  emptyBox: { alignItems: 'center', justifyContent: 'center', paddingVertical: 50, paddingHorizontal: 20 },
  emptyIcon: { color: '#77a33d', fontSize: 34, fontWeight: '900' },
  emptyTitle: { color: '#2b5d36', fontSize: 16, fontWeight: '800', marginTop: 8 },
  emptyText: { color: '#7b887c', fontSize: 12, textAlign: 'center', marginTop: 5 },
});
