import { StyleSheet } from 'react-native';

export const GREEN = '#176D34';
export const GREEN_DARK = '#125829';
export const BG_COLOR = '#F8FAEF';

export const styles = StyleSheet.create({
  flex: { flex: 1 },
  safeArea: { flex: 1, backgroundColor: 'transparent' },
  blurBackdrop: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0 },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: BG_COLOR },
  page: { flexGrow: 1, justifyContent: 'center', paddingVertical: 24 },
  formCard: {
    width: '100%',
    maxWidth: 520,
    alignSelf: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    overflow: 'hidden',
    elevation: 4,
    shadowColor: GREEN,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    borderWidth: 1,
    borderColor: '#E2E8E0',
  },
  categoryHeader: {
    height: 62,
    backgroundColor: GREEN,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 18,
  },
  categoryIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  categoryImage: { width: 34, height: 34, resizeMode: 'contain' },
  categoryTitle: { color: '#FFFFFF', fontSize: 18, fontWeight: '800', marginLeft: 12 },
  categorySubtitle: { color: '#DCFCE7', fontSize: 12, fontWeight: '700', marginLeft: 12, marginTop: 2 },
  formBody: { paddingHorizontal: 14, paddingTop: 14, paddingBottom: 24 },
  confirmationText: {
    color: '#475569',
    fontSize: 13,
    lineHeight: 18,
    paddingHorizontal: 8,
    marginBottom: 14,
  },
  fieldGroup: {
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 10,
    minHeight: 62,
    paddingHorizontal: 16,
    paddingVertical: 8,
    marginBottom: 8,
    backgroundColor: '#F8FAFC',
  },
  label: {
    color: GREEN,
    fontSize: 10,
    lineHeight: 14,
    fontWeight: '800',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  readonlyStrong: {
    color: '#1E293B',
    fontSize: 14,
    fontWeight: '700',
    marginTop: 4,
  },
  errorText: { color: '#DC2626', fontSize: 12, lineHeight: 16, marginHorizontal: 4, marginBottom: 8 },
  submitButton: {
    minWidth: 140,
    height: 44,
    paddingHorizontal: 20,
    borderRadius: 10,
    backgroundColor: GREEN,
    alignItems: 'center',
    justifyContent: 'center',
  },
  submitButtonPressed: { opacity: 0.8 },
  submitText: { color: '#FFFFFF', fontSize: 14, fontWeight: '800' },
  actions: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 12, marginTop: 14 },
  cancelButton: {
    minWidth: 100,
    height: 44,
    paddingHorizontal: 20,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: '#CBD5E1',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelText: { color: '#475569', fontSize: 14, fontWeight: '700' },
  loadingCard: { alignItems: 'center', gap: 10, backgroundColor: '#FFFFFF', padding: 40, borderRadius: 12 },
  loadingText: { color: '#64748B', fontSize: 12 },
  errorCard: { backgroundColor: '#FFFFFF', borderRadius: 12, padding: 24, alignItems: 'center' },
  backText: { color: GREEN, fontSize: 13, fontWeight: '800', marginTop: 10 },
});

