import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#FFFFFF' },
  embeddedSafeArea: { backgroundColor: 'transparent' },
  flex: { flex: 1 },
  background: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  backgroundFade: {
    flex: 1,
    backgroundColor: 'rgba(24, 92, 53, 0.08)',
  },
  scrollArea: { flex: 1 },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 22,
    paddingTop: 4,
    paddingBottom: 24,
  },
  embeddedScrollContent: {
    paddingHorizontal: 22,
    paddingTop: 2,
    paddingBottom: 20,
  },
  cardContainer: { flex: 1, width: '100%' },
  embeddedCardContainer: { flex: 1, width: '100%' },
  domeCap: { width: '100%', height: 34, marginBottom: -1 },
  card: {
    flex: 1,
    width: '100%',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 0,
    paddingTop: 8,
    paddingBottom: 0,
    borderWidth: 0,
    overflow: 'hidden',
    shadowColor: '#185C35',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.14,
    shadowRadius: 18,
    elevation: 7,
  },
  embeddedCard: {
    flex: 1,
    borderRadius: 0,
    borderWidth: 0,
    shadowOpacity: 0,
    elevation: 0,
    backgroundColor: 'transparent',
    paddingTop: 2,
  },
  fixedHeader: {
    paddingHorizontal: 22,
    paddingTop: 6,
    marginBottom: 6,
  },
  embeddedFixedHeader: {
    paddingHorizontal: 22,
    paddingTop: 2,
    marginBottom: 4,
  },
  headingGroup: { marginBottom: 14 },
  kicker: {
    color: '#3D9B43',
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  title: {
    color: '#22652A',
    fontSize: 28,
    lineHeight: 32,
    fontWeight: '900',
    letterSpacing: -0.5,
  },
  subtitle: {
    color: '#526157',
    fontSize: 12,
    lineHeight: 16,
    marginTop: 4,
  },
  label: {
    color: '#22652A',
    fontSize: 11,
    fontWeight: '800',
    marginBottom: 5,
    marginTop: 10,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  input: {
    height: 48,
    borderWidth: 1,
    borderColor: 'rgba(41, 79, 51, 0.28)',
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    paddingHorizontal: 14,
    color: '#1B2D20',
    fontSize: 14,
  },
  inputFocused: {
    borderColor: '#3D9B43',
    backgroundColor: '#FFFFFF',
  },
  passwordRow: {
    height: 48,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(41, 79, 51, 0.28)',
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
  },
  passwordRowFocused: {
    borderColor: '#3D9B43',
    backgroundColor: '#FFFFFF',
  },
  passwordInput: {
    flex: 1,
    color: '#1B2D20',
    fontSize: 14,
    paddingHorizontal: 14,
  },
  eyeButton: {
    height: '100%',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  eyeText: {
    color: '#185C35',
    fontSize: 12,
    fontWeight: '800',
  },
  optionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 12,
    marginBottom: 4,
  },
  rememberRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  checkbox: {
    width: 18,
    height: 18,
    borderRadius: 4,
    borderWidth: 1.5,
    borderColor: '#185C35',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxChecked: {
    backgroundColor: '#185C35',
    borderColor: '#185C35',
  },
  checkboxCheckmark: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '900',
    lineHeight: 13,
  },
  rememberText: {
    color: '#526157',
    fontSize: 12,
    fontWeight: '600',
  },
  forgotText: {
    color: '#185C35',
    fontSize: 12,
    fontWeight: '800',
  },
  error: {
    color: '#8C2020',
    backgroundColor: '#FFF0F0',
    borderWidth: 1,
    borderColor: 'rgba(140, 32, 32, 0.15)',
    borderRadius: 9,
    padding: 10,
    fontSize: 12,
    lineHeight: 16,
    marginBottom: 6,
  },
  buttonWrapper: {
    borderRadius: 10,
    overflow: 'hidden',
    marginTop: 18,
    shadowColor: '#185C35',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.24,
    shadowRadius: 14,
    elevation: 4,
  },
  gradientButton: {
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonPressed: { opacity: 0.88 },
  buttonDisabled: { opacity: 0.65 },
  buttonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  registerRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 18,
  },
  registerPrompt: { color: '#526157', fontSize: 13 },
  registerLink: { color: '#185C35', fontSize: 13, fontWeight: '800' },
  leafContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    width: 420,
    height: 280,
    zIndex: 0,
  },
  leafImage: {
    width: '100%',
    height: '100%',
    opacity: 0.95,
  },
});
