import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#F8ED98' },
  embeddedSafeArea: { backgroundColor: 'transparent' },
  flex: { flex: 1 },
  background: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  backgroundFade: {
    flex: 1,
    backgroundColor: 'rgba(255, 239, 112, 0.42)',
  },
  scrollArea: { flex: 1 },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 22,
    paddingTop: 4,
    paddingBottom: 24,
  },
  embeddedScrollContent: {
    paddingHorizontal: 22,
    paddingTop: 2,
    paddingBottom: 20,
  },
  cardContainer: { flex: 1, width: '100%' },
  embeddedCardContainer: { flex: 1, width: '100%' },
  domeCap: { width: '100%', height: 34, marginBottom: -1 },
  card: {
    flex: 1,
    width: '100%',
    backgroundColor: '#ffffd8',
    paddingHorizontal: 0,
    paddingTop: 8,
    paddingBottom: 0,
    borderWidth: 0,
    shadowColor: '#173d20',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.18,
    shadowRadius: 20,
    elevation: 7,
  },
  embeddedCard: {
    flex: 1,
    borderRadius: 0,
    borderWidth: 0,
    shadowOpacity: 0,
    elevation: 0,
    backgroundColor: 'transparent',
    paddingTop: 2,
  },
  fixedHeader: {
    paddingHorizontal: 22,
    paddingTop: 6,
    marginBottom: 6,
  },
  embeddedFixedHeader: {
    paddingHorizontal: 22,
    paddingTop: 2,
    marginBottom: 4,
  },
  headingGroup: { marginBottom: 14 },
  kicker: { color: '#3d9b43', fontSize: 12, fontWeight: '800', letterSpacing: 1.5, textTransform: 'uppercase', marginBottom: 4 },
  title: { color: '#101b13', fontSize: 30, lineHeight: 34, fontWeight: '900' },
  subtitle: { color: '#526157', fontSize: 13, lineHeight: 18, marginTop: 4 },
  label: { color: '#35443a', fontSize: 12, fontWeight: '800', marginBottom: 5, marginTop: 10 },
  input: { height: 46, borderWidth: 1, borderColor: 'rgba(41, 79, 51, 0.28)', backgroundColor: 'rgba(255, 255, 255, 0.88)', borderRadius: 11, paddingHorizontal: 14, color: '#1b2d20', fontSize: 14 },
  passwordRow: { height: 46, flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: 'rgba(41, 79, 51, 0.28)', backgroundColor: 'rgba(255, 255, 255, 0.88)', borderRadius: 11 },
  passwordInput: { flex: 1, color: '#1b2d20', fontSize: 14, paddingHorizontal: 14 },
  eyeButton: { height: '100%', justifyContent: 'center', paddingHorizontal: 13 },
  eyeText: { color: '#185c35', fontSize: 12, fontWeight: '800' },
  error: { color: '#8c2020', backgroundColor: '#fff0f0', borderRadius: 9, padding: 10, fontSize: 12, lineHeight: 16, marginBottom: 5 },
  button: { height: 50, alignItems: 'center', justifyContent: 'center', backgroundColor: '#185c35', borderRadius: 11, marginTop: 18, shadowColor: '#185c35', shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.2, shadowRadius: 10, elevation: 4 },
  buttonPressed: { opacity: 0.82 },
  buttonDisabled: { opacity: 0.68 },
  buttonText: { color: '#fff', fontSize: 15, fontWeight: '800' },
  registerRow: { flexDirection: 'row', justifyContent: 'center', marginTop: 16 },
  registerPrompt: { color: '#526157', fontSize: 13 },
  registerLink: { color: '#185c35', fontSize: 13, fontWeight: '800' },
});

