import { StyleSheet } from 'react-native';

const FOREST_GREEN = '#185C35';
const LEAF_GREEN = '#3D9B43';
const CARD_BG = '#FFFFFF';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: CARD_BG },
  embeddedSafeArea: { backgroundColor: 'transparent' },
  flex: { flex: 1 },
  background: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0 },
  backgroundTint: { flex: 1, backgroundColor: 'rgba(24, 92, 53, 0.08)' },
  scrollArea: { flex: 1 },
  scrollContent: { flexGrow: 1, paddingHorizontal: 22, paddingTop: 6, paddingBottom: 28 },
  embeddedScrollContent: { paddingHorizontal: 22, paddingTop: 4, paddingBottom: 24 },
  cardContainer: { flex: 1, width: '100%' },
  embeddedCardContainer: { flex: 1, width: '100%' },
  domeCap: { width: '100%', height: 34, marginBottom: -1 },
  card: {
    flex: 1,
    width: '100%',
    paddingHorizontal: 0,
    paddingTop: 8,
    paddingBottom: 0,
    backgroundColor: CARD_BG,
    borderWidth: 0,
    overflow: 'hidden',
    shadowColor: FOREST_GREEN,
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.14,
    shadowRadius: 18,
    elevation: 7,
  },
  embeddedCard: {
    flex: 1,
    borderRadius: 0,
    shadowOpacity: 0,
    elevation: 0,
    backgroundColor: 'transparent',
    paddingTop: 2,
  },
  fixedHeader: { paddingHorizontal: 22, paddingTop: 4 },
  embeddedFixedHeader: { paddingHorizontal: 22, paddingTop: 2 },
  title: {
    color: '#22652A',
    fontSize: 26,
    lineHeight: 30,
    fontWeight: '900',
    letterSpacing: -0.5,
    textAlign: 'center',
    marginTop: 2,
  },
  subtitle: {
    color: '#526157',
    fontSize: 12,
    lineHeight: 16,
    textAlign: 'center',
    marginTop: 3,
  },
  stepper: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 12,
    marginBottom: 12,
    paddingHorizontal: 8,
  },
  stepItem: { flex: 1, alignItems: 'center', position: 'relative' },
  stepCircleWrapper: {
    zIndex: 2,
    width: 32,
    height: 32,
    borderRadius: 16,
    overflow: 'hidden',
  },
  stepCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: 'rgba(41, 79, 51, 0.22)',
    backgroundColor: '#FFFFFF',
  },
  stepCircleActive: {
    borderWidth: 0,
  },
  stepCircleGradient: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepNumber: { color: '#6F7B73', fontSize: 12, fontWeight: '900' },
  stepNumberActive: { color: '#FFFFFF' },
  stepLabel: {
    color: '#6F7B73',
    fontSize: 10,
    fontWeight: '700',
    textAlign: 'center',
    marginTop: 5,
  },
  stepLabelActive: { color: FOREST_GREEN, fontWeight: '800' },
  stepLine: {
    position: 'absolute',
    zIndex: 1,
    top: 15,
    left: '62%',
    width: '76%',
    height: 2,
    backgroundColor: 'rgba(41, 79, 51, 0.16)',
  },
  stepLineActive: { backgroundColor: LEAF_GREEN },
  sectionTitle: {
    color: FOREST_GREEN,
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    paddingBottom: 8,
    marginBottom: 4,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(41, 79, 51, 0.16)',
  },
  field: { marginTop: 12 },
  label: {
    color: '#22652A',
    fontSize: 11,
    fontWeight: '800',
    marginBottom: 5,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  input: {
    height: 48,
    borderWidth: 1,
    borderColor: 'rgba(41, 79, 51, 0.28)',
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 14,
    color: '#1B2D20',
    fontSize: 14,
  },
  inputFocused: {
    borderColor: LEAF_GREEN,
    backgroundColor: '#FFFFFF',
  },
  choiceField: {
    height: 48,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(41, 79, 51, 0.28)',
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 14,
  },
  choiceDisabled: { opacity: 0.58, backgroundColor: 'rgba(235, 240, 225, 0.8)' },
  choiceText: { flex: 1, color: '#1B2D20', fontSize: 14 },
  choicePlaceholder: { color: '#7F8982' },
  choiceChevron: { color: FOREST_GREEN, fontSize: 16, fontWeight: '800' },
  passwordRow: {
    height: 48,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(41, 79, 51, 0.28)',
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
  },
  passwordRowFocused: {
    borderColor: LEAF_GREEN,
    backgroundColor: '#FFFFFF',
  },
  passwordInput: { flex: 1, paddingHorizontal: 14, color: '#1B2D20', fontSize: 14 },
  showButton: { height: '100%', justifyContent: 'center', paddingHorizontal: 14 },
  showText: { color: FOREST_GREEN, fontSize: 12, fontWeight: '800' },
  requirementsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 10,
    marginBottom: 4,
  },
  requirementBadge: {
    flexBasis: '48%',
    flexGrow: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 7,
    paddingHorizontal: 10,
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: 'rgba(41, 79, 51, 0.18)',
  },
  requirementBadgeMet: {
    borderColor: LEAF_GREEN,
    backgroundColor: 'rgba(61, 155, 67, 0.08)',
  },
  requirementBadgeIcon: {
    fontSize: 11,
    fontWeight: '900',
    color: '#849087',
  },
  requirementBadgeIconMet: {
    color: '#27823B',
  },
  requirementBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#526050',
  },
  requirementBadgeTextMet: {
    color: FOREST_GREEN,
  },
  addressLoader: { marginTop: 12 },
  consent: { flexDirection: 'row', alignItems: 'flex-start', marginTop: 18 },
  checkbox: {
    width: 20,
    height: 20,
    borderWidth: 1.5,
    borderColor: FOREST_GREEN,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    marginTop: 1,
  },
  checkboxChecked: { borderColor: FOREST_GREEN, backgroundColor: FOREST_GREEN },
  checkmark: { color: '#FFFFFF', fontSize: 12, fontWeight: '900' },
  consentText: { flex: 1, color: '#526157', fontSize: 12, lineHeight: 18, marginLeft: 10 },
  consentStrong: { color: FOREST_GREEN, fontWeight: '800' },
  error: {
    color: '#8C2020',
    backgroundColor: '#FFF0F0',
    borderWidth: 1,
    borderColor: 'rgba(140, 32, 32, 0.15)',
    borderRadius: 8,
    padding: 10,
    fontSize: 11,
    lineHeight: 16,
    marginBottom: 6,
  },
  actions: { flexDirection: 'row', gap: 10, marginTop: 18 },
  backButton: {
    flex: 0.35,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: FOREST_GREEN,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
  },
  backButtonText: { color: FOREST_GREEN, fontSize: 14, fontWeight: '800' },
  continueButtonWrapper: {
    flex: 1,
    borderRadius: 10,
    overflow: 'hidden',
    shadowColor: FOREST_GREEN,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.22,
    shadowRadius: 12,
    elevation: 4,
  },
  gradientButton: {
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  continueButtonText: { color: '#FFFFFF', fontSize: 15, fontWeight: '800', letterSpacing: 0.3 },
  buttonPressed: { opacity: 0.88 },
  buttonDisabled: { opacity: 0.65 },
  signInRow: { flexDirection: 'row', justifyContent: 'center', marginTop: 16 },
  signInPrompt: { color: '#526157', fontSize: 12 },
  signInLink: { color: FOREST_GREEN, fontSize: 12, fontWeight: '800' },
  modalBackdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(15, 35, 18, 0.48)' },
  modalCard: { maxHeight: '68%', borderTopLeftRadius: 22, borderTopRightRadius: 22, backgroundColor: '#FFFFFF', paddingBottom: 18 },
  modalHeader: { height: 62, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: 'rgba(41, 79, 51, 0.16)', paddingHorizontal: 20 },
  modalTitle: { color: '#22652A', fontSize: 17, fontWeight: '900' },
  modalClose: { color: '#5C6A5D', fontSize: 28 },
  modalList: { paddingHorizontal: 12 },
  modalOption: { minHeight: 50, justifyContent: 'center', borderBottomWidth: 1, borderBottomColor: '#EDF0E5', paddingHorizontal: 10 },
  modalOptionText: { color: '#1B2D20', fontSize: 14 },
  leafContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    width: 420,
    height: 280,
    zIndex: 0,
  },
  leafImage: {
    width: '100%',
    height: '100%',
    opacity: 0.95,
  },
});
