import { StyleSheet } from 'react-native';

const GREEN = '#176d34';
const PALE = '#fbffd6';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: 'transparent' },
  embeddedSafeArea: { backgroundColor: 'transparent' },
  flex: { flex: 1 },
  background: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0 },
  backgroundTint: { flex: 1, backgroundColor: 'rgba(255, 223, 74, 0.42)' },
  scrollContent: { flexGrow: 1, justifyContent: 'flex-end', paddingVertical: 22 },
  card: { width: '100%', borderRadius: 0, paddingHorizontal: 22, paddingTop: 12, paddingBottom: 20, backgroundColor: 'rgba(251, 255, 214, 0.97)', shadowColor: '#31551e', shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.2, shadowRadius: 22, elevation: 8 },
  embeddedCard: { borderRadius: 0, shadowOpacity: 0, elevation: 0 },
  title: { color: '#09211c', fontSize: 30, lineHeight: 36, fontWeight: '900', letterSpacing: -0.7, textAlign: 'center', marginTop: 2 },
  subtitle: { color: '#4d604c', fontSize: 13, lineHeight: 18, textAlign: 'center', marginTop: 3 },
  stepper: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 20, marginBottom: 22, paddingHorizontal: 4 },
  stepItem: { flex: 1, alignItems: 'center', position: 'relative' },
  stepCircle: { zIndex: 2, width: 30, height: 30, borderRadius: 15, alignItems: 'center', justifyContent: 'center', borderWidth: 2, borderColor: '#c3ccb0', backgroundColor: PALE },
  stepCircleActive: { borderColor: '#249143', backgroundColor: '#249143' },
  stepNumber: { color: '#74806d', fontSize: 12, fontWeight: '800' },
  stepNumberActive: { color: '#fff' },
  stepLabel: { color: '#73806e', fontSize: 9, fontWeight: '700', textAlign: 'center', marginTop: 6 },
  stepLabelActive: { color: GREEN },
  stepLine: { position: 'absolute', zIndex: 1, top: 14, left: '65%', width: '70%', height: 2, backgroundColor: '#cad1b9' },
  stepLineActive: { backgroundColor: '#249143' },
  sectionTitle: { color: GREEN, fontSize: 12, fontWeight: '900', letterSpacing: 0.5, textTransform: 'uppercase', paddingBottom: 9, marginBottom: 4, borderBottomWidth: 1, borderBottomColor: '#cbd4ad' },
  field: { marginTop: 13 },
  label: { color: '#18311f', fontSize: 12, fontWeight: '800', marginBottom: 6 },
  input: { height: 48, borderWidth: 1, borderColor: '#b9c3ad', borderRadius: 11, backgroundColor: '#fffef7', paddingHorizontal: 14, color: '#101a13', fontSize: 14 },
  choiceField: { height: 48, flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: '#b9c3ad', borderRadius: 11, backgroundColor: '#fffef7', paddingHorizontal: 14 },
  choiceDisabled: { opacity: 0.58, backgroundColor: '#edf0df' },
  choiceText: { flex: 1, color: '#101a13', fontSize: 14 },
  choicePlaceholder: { color: '#879080' },
  choiceChevron: { color: GREEN, fontSize: 20, marginTop: -4 },
  passwordRow: { height: 48, flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: '#b9c3ad', borderRadius: 11, backgroundColor: '#fffef7' },
  passwordInput: { flex: 1, paddingHorizontal: 14, color: '#101a13', fontSize: 14 },
  showButton: { height: '100%', justifyContent: 'center', paddingHorizontal: 13 },
  showText: { color: GREEN, fontSize: 11, fontWeight: '800' },
  strengthBars: { flexDirection: 'row', gap: 5, marginTop: 16 },
  strengthBar: { flex: 1, height: 5, borderRadius: 3, backgroundColor: '#d9ddc9' },
  strengthBarMet: { backgroundColor: '#45a846' },
  strengthText: { color: '#526050', fontSize: 11, fontWeight: '700', marginTop: 7, marginBottom: 7 },
  requirement: { color: '#7c8477', fontSize: 11, lineHeight: 19 },
  requirementMet: { color: '#27823b' },
  addressLoader: { marginTop: 12 },
  consent: { flexDirection: 'row', alignItems: 'flex-start', marginTop: 18 },
  checkbox: { width: 20, height: 20, borderWidth: 1, borderColor: '#7f8c74', borderRadius: 4, alignItems: 'center', justifyContent: 'center', backgroundColor: '#fff' },
  checkboxChecked: { borderColor: GREEN, backgroundColor: GREEN },
  checkmark: { color: '#fff', fontSize: 13, fontWeight: '900' },
  consentText: { flex: 1, color: '#586455', fontSize: 11, lineHeight: 16, marginLeft: 9 },
  consentStrong: { color: GREEN, fontWeight: '800' },
  error: { color: '#a9302b', backgroundColor: '#fff0e8', borderWidth: 1, borderColor: '#efc8b8', borderRadius: 8, padding: 10, fontSize: 11, lineHeight: 16, marginBottom: 6 },
  actions: { flexDirection: 'row', gap: 10, marginTop: 22 },
  backButton: { flex: 0.42, height: 48, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: GREEN, borderRadius: 11, backgroundColor: '#fffef7' },
  backButtonText: { color: GREEN, fontSize: 14, fontWeight: '800' },
  continueButton: { flex: 1, height: 48, alignItems: 'center', justifyContent: 'center', borderRadius: 11, backgroundColor: GREEN, shadowColor: '#173d20', shadowOffset: { width: 0, height: 5 }, shadowOpacity: 0.2, shadowRadius: 8, elevation: 4 },
  continueButtonText: { color: '#fff', fontSize: 14, fontWeight: '900' },
  buttonDisabled: { opacity: 0.55 },
  signInRow: { flexDirection: 'row', justifyContent: 'center', marginTop: 18 },
  signInPrompt: { color: '#5c6558', fontSize: 12 },
  signInLink: { color: GREEN, fontSize: 12, fontWeight: '900' },
  modalBackdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(15, 35, 18, 0.48)' },
  modalCard: { maxHeight: '68%', borderTopLeftRadius: 22, borderTopRightRadius: 22, backgroundColor: '#fffef5', paddingBottom: 18 },
  modalHeader: { height: 62, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: '#e2e6d5', paddingHorizontal: 20 },
  modalTitle: { color: '#183b24', fontSize: 17, fontWeight: '900' },
  modalClose: { color: '#5c6a5d', fontSize: 28 },
  modalList: { paddingHorizontal: 12 },
  modalOption: { minHeight: 50, justifyContent: 'center', borderBottomWidth: 1, borderBottomColor: '#edf0e5', paddingHorizontal: 10 },
  modalOptionText: { color: '#203326', fontSize: 14 },
});
