import { StyleSheet } from 'react-native';

const GREEN = '#176b32';

export const styles = StyleSheet.create({
  flex: { flex: 1 },
  safeArea: { flex: 1, backgroundColor: 'transparent' },
  blurBackdrop: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0 },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: '#d9d9d9' },
  page: { flexGrow: 1, justifyContent: 'center', paddingVertical: 18 },
  formCard: { width: '100%', maxWidth: 520, alignSelf: 'center', backgroundColor: '#fff', borderRadius: 0, overflow: 'hidden' },
  categoryHeader: { height: 59, backgroundColor: '#2f7f2d', flexDirection: 'row', alignItems: 'center', paddingHorizontal: 17 },
  categoryIcon: { width: 35, height: 35, borderRadius: 18, backgroundColor: '#fff', alignItems: 'center', justifyContent: 'center' },
  categoryEmoji: { fontSize: 23 },
  categoryTitle: { color: '#fff', fontSize: 18, fontWeight: '800', marginLeft: 14 },
  formBody: { paddingHorizontal: 11, paddingTop: 9, paddingBottom: 30 },
  fieldGroup: { borderWidth: 1, borderColor: '#ededed', minHeight: 65, paddingHorizontal: 23, paddingTop: 7, marginBottom: 7 },
  label: { color: '#176b32', fontSize: 11, lineHeight: 15, fontWeight: '700' },
  readonlyStrong: { color: '#111', fontSize: 15, fontWeight: '700', marginTop: 10, marginLeft: 10 },
  timeRow: { height: 35, flexDirection: 'row', alignItems: 'center', marginTop: 2 },
  clock: { width: 21, height: 21, borderRadius: 11, borderWidth: 1.5, borderColor: '#69807a', marginHorizontal: 9 },
  clockHour: { position: 'absolute', width: 1.5, height: 6, backgroundColor: '#69807a', top: 4, left: 9 },
  clockMinute: { position: 'absolute', width: 6, height: 1.5, backgroundColor: '#69807a', top: 10, left: 9, transform: [{ rotate: '30deg' }] },
  timeInput: { width: 187, height: 29, borderWidth: 1, borderColor: '#ededed', color: '#111', fontSize: 14, fontWeight: '700', paddingHorizontal: 22, paddingVertical: 3 },
  chevron: { color: '#18703a', fontSize: 22, marginLeft: -27, marginTop: -4 },
  descriptionGroup: { minHeight: 91 },
  description: { color: '#111', fontSize: 15, lineHeight: 21, fontWeight: '700', marginTop: 18, marginLeft: 17 },
  insightsGroup: { minHeight: 101, paddingBottom: 7 },
  insightsInput: { flex: 1, minHeight: 65, color: '#171717', fontSize: 14, padding: 4 },
  errorText: { color: '#aa322d', fontSize: 11, lineHeight: 16, marginHorizontal: 4, marginBottom: 8 },
  submitButton: { minWidth: 111, height: 27, paddingHorizontal: 18, borderRadius: 4, backgroundColor: '#21783a', alignSelf: 'center', alignItems: 'center', justifyContent: 'center', marginTop: 10, elevation: 5, shadowColor: '#555', shadowOffset: { width: 0, height: 4 }, shadowOpacity: .3, shadowRadius: 5 },
  submitButtonPressed: { opacity: .7 },
  submitText: { color: '#fff', fontSize: 9, fontWeight: '800' },
  loadingCard: { alignItems: 'center', gap: 10, backgroundColor: '#fff', padding: 40 },
  loadingText: { color: '#617064', fontSize: 12 },
  errorCard: { backgroundColor: '#fff', borderRadius: 8, padding: 24, alignItems: 'center' },
  backText: { color: GREEN, fontSize: 12, fontWeight: '800', marginTop: 10 },
});
