import { StyleSheet } from 'react-native';

export const GREEN = '#176D34';
export const GREEN_DARK = '#125829';

export const styles = StyleSheet.create({
  flex: { flex: 1 },
  safeArea: { flex: 1, backgroundColor: 'transparent' },
  blurBackdrop: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0 },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: '#F8FAEF' },
  page: { flexGrow: 1, paddingVertical: 20, paddingBottom: 90 },
  formCard: {
    width: '100%',
    maxWidth: 520,
    alignSelf: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    overflow: 'hidden',
    elevation: 4,
    shadowColor: GREEN,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    borderWidth: 1,
    borderColor: '#E2E8E0',
  },
  categoryHeader: {
    height: 62,
    backgroundColor: GREEN,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 18,
  },
  categoryIcon: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  categoryEmoji: { fontSize: 22 },
  categoryTitle: { color: '#FFFFFF', fontSize: 18, fontWeight: '800', marginLeft: 12 },
  formBody: { paddingHorizontal: 14, paddingTop: 14, paddingBottom: 28 },
  fieldGroup: {
    borderWidth: 1,
    borderColor: '#E6ECE4',
    borderRadius: 10,
    minHeight: 65,
    paddingHorizontal: 16,
    paddingVertical: 10,
    marginBottom: 10,
    backgroundColor: '#FFFFFF',
  },
  label: { color: GREEN, fontSize: 10, fontWeight: '800', letterSpacing: 0.5, textTransform: 'uppercase', marginBottom: 4 },
  readonlyStrong: { color: '#1E293B', fontSize: 15, fontWeight: '700', marginTop: 4 },
  timeRow: { height: 38, flexDirection: 'row', alignItems: 'center', marginTop: 4 },
  clock: { width: 22, height: 22, borderRadius: 11, borderWidth: 1.5, borderColor: '#64748B', marginHorizontal: 8 },
  clockHour: { position: 'absolute', width: 1.5, height: 6, backgroundColor: '#64748B', top: 4, left: 9 },
  clockMinute: {
    position: 'absolute',
    width: 6,
    height: 1.5,
    backgroundColor: '#64748B',
    top: 10,
    left: 9,
    transform: [{ rotate: '30deg' }],
  },
  timeInput: {
    width: 180,
    height: 34,
    borderWidth: 1,
    borderColor: '#D8DADD',
    borderRadius: 8,
    color: '#1E293B',
    fontSize: 14,
    fontWeight: '700',
    paddingHorizontal: 14,
    paddingVertical: 4,
    backgroundColor: '#F8FAFC',
  },
  chevron: { color: GREEN, fontSize: 20, marginLeft: -24, marginTop: -2 },
  descriptionGroup: { minHeight: 85 },
  description: { color: '#334155', fontSize: 14, lineHeight: 20, fontWeight: '600', marginTop: 4 },

  // Photo Proof Group
  photoGroup: {
    minHeight: 125,
    paddingBottom: 14,
    paddingHorizontal: 16,
  },
  photoRequiredBadge: {
    color: '#DC2626',
    fontSize: 10,
    fontWeight: '700',
  },
  photoUploadBox: {
    marginTop: 8,
    borderWidth: 1.5,
    borderColor: '#A5D6A7',
    borderStyle: 'dashed',
    borderRadius: 10,
    backgroundColor: '#F8FAEF',
    paddingVertical: 18,
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  photoUploadIcon: {
    fontSize: 28,
    marginBottom: 6,
  },
  photoUploadPrompt: {
    color: '#475569',
    fontSize: 12,
    fontWeight: '500',
    textAlign: 'center',
    marginBottom: 12,
  },
  choosePhotoButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: GREEN,
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 8,
    gap: 8,
    elevation: 2,
    shadowColor: GREEN,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  choosePhotoButtonText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '800',
  },
  photoPreviewContainer: {
    width: '100%',
    marginTop: 8,
    borderRadius: 10,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#CBD5E1',
  },
  photoPreviewImage: {
    width: '100%',
    height: 180,
    resizeMode: 'cover',
  },
  photoBadgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  photoBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  photoBadgeText: {
    color: GREEN,
    fontSize: 12,
    fontWeight: '800',
  },
  photoActionsRow: {
    flexDirection: 'row',
    gap: 8,
  },
  changePhotoButton: {
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 6,
    backgroundColor: '#EAF4D9',
  },
  changePhotoText: {
    color: GREEN,
    fontSize: 11,
    fontWeight: '800',
  },
  removePhotoButton: {
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 6,
    backgroundColor: '#FEE2E2',
  },
  removePhotoText: {
    color: '#DC2626',
    fontSize: 11,
    fontWeight: '800',
  },

  insightsGroup: { minHeight: 95, paddingBottom: 8 },
  insightsInput: { flex: 1, minHeight: 65, color: '#1E293B', fontSize: 13, padding: 4, lineHeight: 18 },
  errorText: { color: '#DC2626', fontSize: 12, lineHeight: 16, marginHorizontal: 4, marginBottom: 8, textAlign: 'center', fontWeight: '600' },
  submitButton: {
    minWidth: 160,
    height: 42,
    paddingHorizontal: 24,
    borderRadius: 10,
    backgroundColor: GREEN,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 14,
    elevation: 4,
    shadowColor: GREEN,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 5,
  },
  submitButtonPressed: { opacity: 0.85 },
  submitText: { color: '#FFFFFF', fontSize: 13, fontWeight: '800', letterSpacing: 0.3 },
  loadingCard: { alignItems: 'center', gap: 10, backgroundColor: '#FFFFFF', padding: 40, borderRadius: 14 },
  loadingText: { color: '#64748B', fontSize: 12 },
  errorCard: { backgroundColor: '#FFFFFF', borderRadius: 14, padding: 24, alignItems: 'center' },
  backText: { color: GREEN, fontSize: 12, fontWeight: '800', marginTop: 10 },
});

