import { StyleSheet } from 'react-native';

export const GREEN = '#176D34';
export const GREEN_DARK = '#125829';
export const BG_COLOR = '#F8FAEF';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: GREEN,
  },
  headerBar: {
    height: 64,
    paddingHorizontal: 18,
    backgroundColor: GREEN,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 0,
    backgroundColor: 'transparent',
  },
  backButtonText: {
    color: '#FFFFFF',
    fontSize: 13.5,
    fontWeight: '700',
  },
  headerStatusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 14,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.35)',
  },
  headerStatusBadgeAwaiting: {
    backgroundColor: '#FEF3C7',
    borderColor: '#FDE68A',
  },
  headerStatusBadgeText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '800',
  },
  headerStatusBadgeTextAwaiting: {
    color: '#92400E',
  },
  mainBodyContainer: {
    flex: 1,
    backgroundColor: BG_COLOR,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    overflow: 'hidden',
  },
  center: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: BG_COLOR,
    padding: 20,
  },
  content: {
    paddingTop: 18,
    paddingBottom: 40,
    paddingHorizontal: 18,
    gap: 14,
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
  },
  cardHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  badgesRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  categoryPill: {
    paddingHorizontal: 9,
    paddingVertical: 3.5,
    borderRadius: 8,
    borderWidth: 1,
  },
  categoryPillText: {
    fontSize: 11,
    fontWeight: '800',
  },
  fieldPill: {
    paddingHorizontal: 8,
    paddingVertical: 3.5,
    borderRadius: 8,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  fieldPillText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#475569',
  },
  statusTextCompleted: {
    fontSize: 12,
    fontWeight: '800',
    color: '#166534',
  },
  statusTextAwaiting: {
    fontSize: 12,
    fontWeight: '800',
    color: '#92400E',
  },
  taskTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#0F172A',
    lineHeight: 24,
    marginBottom: 6,
  },
  taskDesc: {
    fontSize: 13,
    fontWeight: '500',
    color: '#64748B',
    lineHeight: 18,
    marginBottom: 12,
  },
  metaRow: {
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
    paddingTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  metaItem: {
    fontSize: 12,
    color: '#64748B',
  },
  metaItemBold: {
    fontWeight: '700',
    color: '#0F172A',
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: '800',
    color: '#134B24',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  totalYieldBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    backgroundColor: '#DCFCE7',
  },
  totalYieldText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#166534',
  },
  countsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 10,
  },
  countBox: {
    width: '48%',
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  countBoxDamaged: {
    backgroundColor: '#FEF2F2',
    borderColor: '#FECACA',
  },
  countBoxLabel: {
    fontSize: 10.5,
    fontWeight: '700',
    color: '#64748B',
    textTransform: 'uppercase',
  },
  countBoxLabelDamaged: {
    color: '#B91C1C',
  },
  countBoxValue: {
    fontSize: 22,
    fontWeight: '900',
    color: '#1E293B',
    marginTop: 4,
  },
  countBoxValueDamaged: {
    color: '#DC2626',
  },
  countBoxSub: {
    fontSize: 10,
    color: '#94A3B8',
    marginTop: 2,
  },
  qualityBenchmark: {
    padding: 10,
    borderRadius: 10,
    backgroundColor: '#F0FDF4',
    borderWidth: 1,
    borderColor: '#BBF7D0',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  qualityBenchmarkLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#166534',
  },
  qualityBenchmarkVal: {
    fontSize: 12,
    fontWeight: '800',
    color: '#166534',
  },
  specRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  specRowLast: {
    borderBottomWidth: 0,
    paddingBottom: 2,
  },
  specLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#64748B',
  },
  specValue: {
    fontSize: 12.5,
    fontWeight: '700',
    color: '#0F172A',
  },
  insightsBox: {
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  insightsText: {
    fontSize: 13,
    fontWeight: '500',
    color: '#334155',
    lineHeight: 19,
    fontStyle: 'italic',
  },
  noInsightsText: {
    fontSize: 12.5,
    color: '#94A3B8',
    fontStyle: 'italic',
  },
  photoCard: {
    borderRadius: 14,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: '#F1F5F9',
    position: 'relative',
  },
  photoImage: {
    width: '100%',
    height: 190,
  },
  photoOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  photoOverlayText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '700',
  },
  photoZoomBadge: {
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  photoZoomBadgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '800',
  },
  noPhotoBox: {
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    paddingVertical: 24,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#CBD5E1',
  },
  noPhotoText: {
    color: '#94A3B8',
    fontSize: 12,
    fontWeight: '600',
  },
  timelineContainer: {
    borderLeftWidth: 2,
    borderLeftColor: '#DCFCE7',
    marginLeft: 8,
    paddingLeft: 14,
    gap: 14,
  },
  timelineItem: {
    position: 'relative',
  },
  timelineDot: {
    position: 'absolute',
    left: -21,
    top: 2,
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#176D34',
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  timelineDotPending: {
    backgroundColor: '#D97706',
  },
  timelineTitle: {
    fontSize: 12.5,
    fontWeight: '700',
    color: '#0F172A',
  },
  timelineSub: {
    fontSize: 11,
    fontWeight: '500',
    color: '#64748B',
    marginTop: 2,
  },
  returnButton: {
    paddingVertical: 13,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 3,
    elevation: 1,
  },
  returnButtonText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#334155',
  },
  errorBox: {
    backgroundColor: '#FEF2F2',
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: '#FECACA',
    alignItems: 'center',
  },
  errorText: {
    color: '#DC2626',
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'center',
  },
  retryText: {
    color: '#B91C1C',
    fontSize: 12,
    fontWeight: '800',
    marginTop: 8,
  },

  // Full Screen Photo Modal
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.92)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalCloseButton: {
    position: 'absolute',
    top: 48,
    right: 20,
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
  },
  modalCloseText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '800',
  },
  modalImage: {
    width: '94%',
    height: '75%',
  },
});
