import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#fbfbf4' },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: '#fbfbf4' },
  content: { paddingTop: 17, paddingBottom: 105, flexGrow: 1 },
  pageTitle: { color: '#176b32', fontSize: 28, lineHeight: 36, fontWeight: '800', marginBottom: 19 },
  filters: { flexDirection: 'row', gap: 8, marginHorizontal: 0, marginBottom: 24 },
  filterButton: { flex: 1, height: 25, borderRadius: 14, backgroundColor: '#fff', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#d7dadd', elevation: 4, shadowColor: '#777', shadowOffset: { width: 0, height: 4 }, shadowOpacity: .17, shadowRadius: 6 },
  filterButtonActive: { backgroundColor: '#207b3c', borderColor: '#207b3c' },
  filterText: { color: '#24713a', fontSize: 10, fontWeight: '700' },
  filterTextActive: { color: '#fff' },
  errorText: { color: '#a83d36', fontSize: 11, marginBottom: 10 },
  loader: { marginTop: 50 },
  taskShell: { backgroundColor: '#fff', borderRadius: 8, marginBottom: 18, borderWidth: 1, borderColor: '#d8dbde', elevation: 4, shadowColor: '#777', shadowOffset: { width: 0, height: 5 }, shadowOpacity: .16, shadowRadius: 7, overflow: 'hidden' },
  taskShellExpanded: { backgroundColor: '#eaf4d9', borderColor: '#eaf4d9', padding: 11 },
  taskSummary: { height: 59, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12 },
  taskIconBox: { width: 43, height: 43, backgroundColor: '#f1f5ee', alignItems: 'center', justifyContent: 'center' },
  taskIcon: { fontSize: 27 },
  taskTitleArea: { flex: 1, paddingHorizontal: 12 },
  taskCategory: { color: '#176b32', fontSize: 10, fontWeight: '700', marginBottom: 5 },
  taskDescription: { color: '#232323', fontSize: 16 },
  priorityPill: { width: 68, height: 25, borderRadius: 14, backgroundColor: '#fff', borderWidth: 1, borderColor: '#d8dadd', alignItems: 'center', justifyContent: 'center', elevation: 3, shadowColor: '#777', shadowOffset: { width: 0, height: 3 }, shadowOpacity: .16, shadowRadius: 5 },
  priorityText: { color: '#25713c', textTransform: 'capitalize', fontSize: 10, fontWeight: '700' },
  expandedCard: { backgroundColor: '#fff', borderRadius: 8, borderWidth: 1, borderColor: '#d8dadd', padding: 15, paddingBottom: 12 },
  fieldBox: { minHeight: 67, borderWidth: 1, borderColor: '#ececec', paddingHorizontal: 28, paddingVertical: 11 },
  descriptionBox: { minHeight: 97, borderWidth: 1, borderColor: '#e7e7e7', borderRadius: 8, paddingHorizontal: 28, paddingVertical: 10, marginTop: 8 },
  detailLabel: { color: '#176b32', fontSize: 9, fontWeight: '700', marginBottom: 10 },
  fieldValue: { color: '#151515', fontSize: 16, fontWeight: '600' },
  detailDescription: { color: '#202020', fontSize: 16 },
  completeButton: { minWidth: 132, height: 29, backgroundColor: '#237b3d', borderRadius: 5, alignSelf: 'center', alignItems: 'center', justifyContent: 'center', marginTop: 14, paddingHorizontal: 18, elevation: 4, shadowColor: '#555', shadowOffset: { width: 0, height: 3 }, shadowOpacity: .28, shadowRadius: 4 },
  completeButtonText: { color: '#fff', fontSize: 10, fontWeight: '700' },
  buttonPressed: { opacity: .75 },
  emptyState: { alignItems: 'center', paddingVertical: 65 },
  emptyCheck: { color: '#72a83c', fontSize: 38, fontWeight: '800' },
  emptyTitle: { color: '#26643a', fontSize: 17, fontWeight: '800', marginTop: 10 },
  emptyCopy: { color: '#849086', fontSize: 12, marginTop: 6 },
});

