import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#f8faef' },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: '#f8faef' },
  content: { paddingTop: 17, paddingBottom: 105, flexGrow: 1 },
  titleRow: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between' },
  sectionTitle: { color: '#176b32', fontSize: 28, lineHeight: 36, fontWeight: '800' },
  signOut: { color: '#247637', fontSize: 11, fontWeight: '800', paddingVertical: 8 },
  filters: { flexDirection: 'row', gap: 8, marginTop: 19, marginBottom: 24 },
  filterButton: {
    flex: 1,
    height: 25,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#d7dadd',
    elevation: 4,
    shadowColor: '#777',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: .17,
    shadowRadius: 6,
  },
  filterButtonActive: { backgroundColor: '#207b3c', borderColor: '#207b3c' },
  filterText: { color: '#24713a', fontSize: 10, fontWeight: '700' },
  filterTextActive: { color: '#fff' },
  taskCard: {
    backgroundColor: '#fff',
    borderRadius: 8,
    marginBottom: 18,
    borderWidth: 1,
    borderColor: '#d8dbde',
    shadowColor: '#777',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: .16,
    shadowRadius: 7,
    elevation: 4,
    overflow: 'hidden',
  },
  taskCardExpanded: { backgroundColor: '#eaf4d9', borderColor: '#eaf4d9', padding: 11 },
  taskSummary: { minHeight: 59, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12 },
  taskIconCircle: { width: 43, height: 43, backgroundColor: '#f1f5ee', alignItems: 'center', justifyContent: 'center' },
  taskIcon: { fontSize: 27 },
  taskTitleArea: { flex: 1, paddingHorizontal: 12 },
  taskCategory: { color: '#176b32', fontSize: 10, fontWeight: '700', marginBottom: 5 },
  taskDescription: { color: '#232323', fontSize: 16 },
  priority: { width: 68, height: 25, borderRadius: 14, backgroundColor: '#fff', borderWidth: 1, borderColor: '#d8dadd', alignItems: 'center', justifyContent: 'center', elevation: 3, shadowColor: '#777', shadowOffset: { width: 0, height: 3 }, shadowOpacity: .16, shadowRadius: 5 },
  priority_high: { backgroundColor: '#fff' },
  priority_medium: { backgroundColor: '#fff' },
  priority_low: { backgroundColor: '#fff' },
  priorityText: { color: '#25713c', fontSize: 10, fontWeight: '700', textTransform: 'capitalize' },
  details: { backgroundColor: '#fff', borderRadius: 8, borderWidth: 1, borderColor: '#d8dadd', padding: 15, paddingBottom: 12 },
  detailBox: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#e7e7e7', paddingHorizontal: 28, paddingVertical: 11, marginBottom: 8, borderRadius: 8, minHeight: 67 },
  detailLabel: { color: '#176b32', fontSize: 9, fontWeight: '700', marginBottom: 10 },
  detailValue: { color: '#202020', fontSize: 16, lineHeight: 20 },
  metaRow: { flexDirection: 'row', justifyContent: 'space-between', marginHorizontal: 3, marginBottom: 10 },
  metaText: { color: '#718070', fontSize: 11, fontWeight: '600' },
  startButton: { height: 29, minWidth: 132, paddingHorizontal: 18, alignSelf: 'center', alignItems: 'center', justifyContent: 'center', backgroundColor: '#237b3d', borderRadius: 5, elevation: 4, shadowColor: '#555', shadowOffset: { width: 0, height: 3 }, shadowOpacity: .28, shadowRadius: 4 },
  startButtonText: { color: '#fff', fontSize: 10, fontWeight: '700' },
  completedBanner: { alignSelf: 'center', backgroundColor: '#dcefd5', borderRadius: 12, paddingHorizontal: 16, paddingVertical: 7 },
  completedText: { color: '#23733a', fontSize: 11, fontWeight: '800' },
  errorBox: { backgroundColor: '#fff0ef', borderRadius: 10, padding: 12, marginBottom: 12, borderWidth: 1, borderColor: '#f0ceca' },
  errorText: { color: '#ad2d2d', fontSize: 12, lineHeight: 17 },
  retry: { color: '#7b2727', fontSize: 11, fontWeight: '800', marginTop: 4 },
  loadingBox: { alignItems: 'center', justifyContent: 'center', paddingVertical: 56, gap: 10 },
  loadingText: { color: '#6a796c', fontSize: 12 },
  emptyBox: { alignItems: 'center', justifyContent: 'center', paddingVertical: 50, paddingHorizontal: 20 },
  emptyIcon: { color: '#77a33d', fontSize: 34, fontWeight: '900' },
  emptyTitle: { color: '#2b5d36', fontSize: 16, fontWeight: '800', marginTop: 8 },
  emptyText: { color: '#7b887c', fontSize: 12, textAlign: 'center', marginTop: 5 },
});

