import { StyleSheet } from 'react-native';

export const GREEN = '#176D34';
export const DARK_GREEN = '#143A1E';

export const styles = StyleSheet.create({
  card: {
    width: '100%',
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 14,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#EAEFE8',
    elevation: 3,
    shadowColor: GREEN,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
  },
  topRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  locationBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#F1F6F0',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 16,
  },
  locationPin: {
    fontSize: 12,
  },
  locationText: {
    fontSize: 13,
    fontWeight: '800',
    color: DARK_GREEN,
    letterSpacing: -0.2,
  },
  weatherArtText: {
    fontSize: 34,
  },
  tempRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginVertical: 4,
  },
  mainTempText: {
    fontSize: 38,
    fontWeight: '900',
    color: '#0F2D18',
    letterSpacing: -1,
    lineHeight: 44,
  },
  hlStack: {
    justifyContent: 'center',
    gap: 2,
  },
  hlLabel: {
    fontSize: 11.5,
    fontWeight: '700',
    color: '#64748B',
  },
  hlValue: {
    color: '#1E293B',
    fontWeight: '800',
  },
  conditionPill: {
    marginLeft: 'auto',
    alignSelf: 'center',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 10,
    backgroundColor: '#DCFCE7',
  },
  conditionPillText: {
    fontSize: 11.5,
    fontWeight: '800',
    color: '#15803D',
  },
  divider: {
    height: 1,
    backgroundColor: '#EEF2EC',
    marginVertical: 12,
  },
  metricsGrid: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 4,
    marginBottom: 12,
  },
  metricCol: {
    alignItems: 'center',
    gap: 3,
    minWidth: 55,
  },
  metricLabel: {
    fontSize: 10.5,
    fontWeight: '700',
    color: '#64748B',
    textTransform: 'capitalize',
  },
  metricValue: {
    fontSize: 13.5,
    fontWeight: '900',
    color: '#0F2D18',
  },
  solarArcSection: {
    backgroundColor: '#F8FAF7',
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 6,
  },
  solarHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  solarTimeBadge: {
    fontSize: 12,
    fontWeight: '900',
    color: '#0F2D18',
  },
  solarSublabel: {
    fontSize: 10,
    fontWeight: '600',
    color: '#64748B',
  },
  arcTrackWrap: {
    width: '100%',
    height: 38,
    marginTop: 4,
    position: 'relative',
    justifyContent: 'flex-end',
    overflow: 'hidden',
  },
  arcCurve: {
    width: '100%',
    height: 60,
    borderTopLeftRadius: 160,
    borderTopRightRadius: 160,
    borderWidth: 2,
    borderBottomWidth: 0,
    borderColor: '#CBD5E1',
    borderStyle: 'dashed',
  },
  sunPointerDot: {
    position: 'absolute',
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#FBBF24',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 4,
    shadowColor: '#F59E0B',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 6,
  },
  sunIcon: {
    fontSize: 12,
  },
});
