import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  card: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 14,
    marginBottom: 14,
    padding: 14,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  tile: {
    width: 58,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#CFDDCB',
    overflow: 'hidden',
  },
  tileMonth: {
    paddingVertical: 4,
    backgroundColor: '#176D34',
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1.2,
    textAlign: 'center',
  },
  tileBody: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F7FAF6',
  },
  tileDay: {
    color: '#134B24',
    fontSize: 26,
    fontWeight: '800',
    lineHeight: 30,
  },
  tileWeekday: {
    marginTop: 2,
    color: '#64748B',
    fontSize: 10.5,
    fontWeight: '600',
  },
  content: {
    flex: 1,
    minWidth: 0,
    justifyContent: 'space-between',
    gap: 10,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  title: {
    flex: 1,
    color: '#0F172A',
    fontSize: 15,
    fontWeight: '800',
  },
  badge: {
    paddingHorizontal: 9,
    paddingVertical: 3,
    borderRadius: 9999,
    borderWidth: 1,
  },
  badgeText: {
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  subtitle: {
    marginTop: 3,
    color: '#64748B',
    fontSize: 12.5,
    fontWeight: '600',
  },
  strip: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: '#F1F5F9',
  },
  opens: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  opensText: {
    color: '#334155',
    fontSize: 12,
    fontWeight: '700',
  },
  countdown: {
    color: '#176D34',
    fontSize: 12,
    fontWeight: '800',
  },
});
