import { StyleSheet } from 'react-native';

const ICON_COLOR = '#176D34';

export const styles = StyleSheet.create({
  navigation: {
    height: 72,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingHorizontal: 20,
    backgroundColor: '#ffffff',
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
  },
  button: {
    flex: 1,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
  },
  activeButton: {
    backgroundColor: 'transparent',
  },
  pressedButton: {
    opacity: 0.6,
  },
  homeIconWrapper: {
    width: 36,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
  },
  homeRoofTriangle: {
    width: 0,
    height: 0,
    borderLeftWidth: 17,
    borderRightWidth: 17,
    borderBottomWidth: 14,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: ICON_COLOR,
  },
  homeHouseBody: {
    width: 26,
    height: 16,
    backgroundColor: ICON_COLOR,
    alignItems: 'center',
    justifyContent: 'flex-end',
    borderBottomLeftRadius: 2,
    borderBottomRightRadius: 2,
  },
  homeDoorCutout: {
    width: 8,
    height: 10,
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 2,
    borderTopRightRadius: 2,
  },
  clipboard: {
    width: 26,
    height: 32,
    borderWidth: 2.5,
    borderColor: ICON_COLOR,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  clipClip: {
    position: 'absolute',
    top: -5,
    width: 12,
    height: 6,
    borderRadius: 2,
    borderWidth: 2,
    borderColor: ICON_COLOR,
    backgroundColor: '#ffffff',
  },
  clipCheckText: {
    color: ICON_COLOR,
    fontSize: 16,
    fontWeight: '900',
    marginTop: 2,
  },
  calendarWrapper: {
    width: 30,
    height: 30,
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  calendarRingLeft: {
    position: 'absolute',
    top: 0,
    left: 6,
    width: 3,
    height: 5,
    borderRadius: 1.5,
    backgroundColor: ICON_COLOR,
    zIndex: 2,
  },
  calendarRingRight: {
    position: 'absolute',
    top: 0,
    right: 6,
    width: 3,
    height: 5,
    borderRadius: 1.5,
    backgroundColor: ICON_COLOR,
    zIndex: 2,
  },
  calendarBox: {
    width: 28,
    height: 26,
    borderWidth: 2.5,
    borderColor: ICON_COLOR,
    borderRadius: 5,
    marginTop: 3,
    paddingTop: 4,
    paddingHorizontal: 3,
    backgroundColor: '#ffffff',
  },
  calendarGridRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 3,
  },
  calendarGridDot: {
    width: 4,
    height: 4,
    borderRadius: 1,
    backgroundColor: ICON_COLOR,
  },
  profileIcon: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileHead: {
    width: 14,
    height: 14,
    borderRadius: 7,
    borderWidth: 2.5,
    borderColor: ICON_COLOR,
    marginBottom: 2,
  },
  profileBody: {
    width: 26,
    height: 12,
    borderTopLeftRadius: 13,
    borderTopRightRadius: 13,
    borderWidth: 2.5,
    borderColor: ICON_COLOR,
    borderBottomWidth: 0,
  },
});

