import { useCallback, useEffect, useState } from 'react'
import { Check, MapPin, Navigation, PackageCheck, Truck } from 'lucide-react'
import { AdminTopbar } from '../../components/AdminNavigation.jsx'
import { supabase } from '../../lib/supabase.js'
import '../../styles/admin-dashboard.css'
import '../../styles/seller-order-management.css'
import '../../styles/driver-orders.css'

const API_URL = (import.meta.env.VITE_API_URL || 'http://localhost:5000').replace(/\/$/, '')
function formatWindow(start, end) { if (!start || !end) return 'Schedule pending'; const date = new Intl.DateTimeFormat('en-PH', { dateStyle: 'medium', hour: 'numeric', minute: '2-digit' }); const time = new Intl.DateTimeFormat('en-PH', { hour: 'numeric', minute: '2-digit' }); return `${date.format(new Date(start))} – ${time.format(new Date(end))}` }
function label(status) { return String(status || 'assigned').replaceAll('_', ' ') }

export default function DriverOrders() {
  const [orders, setOrders] = useState([]); const [vehicles, setVehicles] = useState([]); const [selectedVehicles, setSelectedVehicles] = useState({}); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [actioning, setActioning] = useState('')
  const request = useCallback(async (path, options = {}) => { const { data, error: sessionError } = await supabase.auth.getSession(); if (sessionError) throw sessionError; const token = data.session?.access_token; if (!token) throw new Error('Your session has ended. Please sign in again.'); const response = await fetch(`${API_URL}${path}`, { ...options, headers: { Authorization: `Bearer ${token}`, ...(options.body ? { 'Content-Type': 'application/json' } : {}), ...options.headers } }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error || 'Unable to update this delivery'); return body }, [])
  const loadOrders = useCallback(async () => { setError(''); try { const [orderData, vehicleData] = await Promise.all([request('/api/driver/orders'), request('/api/driver/orders/vehicles')]); setOrders(orderData.orders || []); setVehicles(vehicleData.vehicles || []) } catch (requestError) { setError(requestError.message) } finally { setLoading(false) } }, [request])
  useEffect(() => { loadOrders() }, [loadOrders])
  async function acceptDelivery(id) { const vehicleId = selectedVehicles[id]; if (!vehicleId) { setError('Select an available vehicle before accepting this delivery.'); return } setActioning(`accept-${id}`); setError(''); try { await request(`/api/driver/orders/${id}/accept`, { method: 'POST', body: JSON.stringify({ vehicle_id: vehicleId }) }); await loadOrders() } catch (requestError) { setError(requestError.message) } finally { setActioning('') } }
  async function advanceDelivery(id, status) { setActioning(`${status}-${id}`); setError(''); try { await request(`/api/driver/orders/${id}/status`, { method: 'POST', body: JSON.stringify({ status }) }); await loadOrders() } catch (requestError) { setError(requestError.message) } finally { setActioning('') } }
  function deliveryAction(order) { const status = order.delivery_assignment_status || 'assigned'; const vehicle = order.vehicle ? `${order.vehicle.vehicle_name} · ${order.vehicle.plate_number}` : 'Not recorded'; if (status === 'assigned') return <div className="driver-delivery-actions"><label><span>Vehicle to use</span><select value={selectedVehicles[order.id] || ''} onChange={(event) => setSelectedVehicles({ ...selectedVehicles, [order.id]: event.target.value })}><option value="">Select available vehicle</option>{vehicles.map((item) => <option value={item.id} key={item.id}>{item.vehicle_name} · {item.plate_number}</option>)}</select></label><button type="button" onClick={() => acceptDelivery(order.id)} disabled={actioning === `accept-${order.id}` || !vehicles.length}><Check aria-hidden="true" />{actioning === `accept-${order.id}` ? 'Accepting…' : 'Accept Delivery'}</button>{!vehicles.length && <small>No vehicle is currently available.</small>}</div>; if (status === 'accepted') return <div className="driver-delivery-actions"><p>Vehicle: <strong>{vehicle}</strong></p><button type="button" onClick={() => advanceDelivery(order.id, 'picked_up')} disabled={actioning === `picked_up-${order.id}`}><PackageCheck aria-hidden="true" />Mark Picked Up</button></div>; if (status === 'picked_up') return <div className="driver-delivery-actions"><p>Vehicle: <strong>{vehicle}</strong></p><button type="button" onClick={() => advanceDelivery(order.id, 'out_for_delivery')} disabled={actioning === `out_for_delivery-${order.id}`}><Navigation aria-hidden="true" />Start Delivery</button></div>; if (status === 'out_for_delivery') return <div className="driver-delivery-actions"><p>Vehicle: <strong>{vehicle}</strong></p><button type="button" onClick={() => advanceDelivery(order.id, 'delivered')} disabled={actioning === `delivered-${order.id}`}><Truck aria-hidden="true" />Mark Delivered</button></div>; return <div className="driver-delivery-complete"><Check aria-hidden="true" />Delivery completed</div> }
  return <main className="admin-dashboard seller-order-page"><section className="admin-workspace"><AdminTopbar /><div className="seller-order-content"><header className="seller-order-heading"><div><p>Driver workspace</p><h1>My Deliveries</h1><span>Accept an assigned order with an available vehicle, then update each delivery as you work.</span></div></header>{error && <div className="tasks-error" role="alert">{error}</div>}<section className="seller-orders-list" aria-label="Assigned delivery orders">{loading ? <p>Loading assigned orders…</p> : orders.length ? orders.map((order) => <article className="seller-order-card driver-delivery-card" key={order.id}><header><div><strong>{order.order_number}</strong><span className={`driver-delivery-status is-${order.delivery_assignment_status || 'assigned'}`}>{label(order.delivery_assignment_status)}</span></div><b>₱{Number(order.total_amount).toLocaleString()}</b></header><p><strong>{order.delivery_full_name}</strong> · {order.payment_method}</p><p><MapPin aria-hidden="true" /> {[order.delivery_barangay, order.delivery_city_municipality, order.delivery_province, order.delivery_region].filter(Boolean).join(', ')}</p><footer><span>{formatWindow(order.delivery_scheduled_at, order.delivery_window_end_at)}</span></footer>{deliveryAction(order)}</article>) : <p>No delivery orders are assigned to you.</p>}</section></div></section></main>
}
