-- AgriVerse inventory records, stock updates, and soft archiving.
create table if not exists public.inventory_items (
  id bigint generated by default as identity primary key,
  item_type text not null,
  item_name text not null,
  variant text not null,
  stock_quantity integer not null default 0 check (stock_quantity >= 0),
  created_by uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz,
  constraint inventory_item_type_length check (char_length(trim(item_type)) between 1 and 60),
  constraint inventory_item_name_length check (char_length(trim(item_name)) between 1 and 100),
  constraint inventory_variant_length check (char_length(trim(variant)) between 1 and 100)
);

create unique index if not exists inventory_active_name_variant_key
  on public.inventory_items (lower(item_name), lower(variant))
  where archived_at is null;

create index if not exists inventory_active_updated_idx
  on public.inventory_items (updated_at desc)
  where archived_at is null;

create or replace function public.set_inventory_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists inventory_set_updated_at on public.inventory_items;
create trigger inventory_set_updated_at
  before update on public.inventory_items
  for each row execute procedure public.set_inventory_updated_at();

create or replace function public.add_inventory_stock(p_item_id bigint, p_quantity integer)
returns setof public.inventory_items
language plpgsql
security definer
set search_path = ''
as $$
begin
  if p_quantity is null or p_quantity <= 0 then
    raise exception 'Stock quantity must be greater than zero';
  end if;

  return query
  update public.inventory_items
  set stock_quantity = stock_quantity + p_quantity
  where id = p_item_id and archived_at is null
  returning *;

  if not found then
    raise exception 'Inventory item not found';
  end if;
end;
$$;

alter table public.inventory_items enable row level security;
revoke all on table public.inventory_items from anon, authenticated;
revoke all on function public.add_inventory_stock(bigint, integer) from public, anon, authenticated;
grant all on table public.inventory_items to service_role;
grant usage, select on sequence public.inventory_items_id_seq to service_role;
grant execute on function public.add_inventory_stock(bigint, integer) to service_role;
