-- AgriVerse farm task assignment and scheduling.
do $$ begin
  create type public.task_priority as enum ('high', 'medium', 'low');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.task_status as enum ('pending', 'in_progress', 'completed');
exception when duplicate_object then null;
end $$;

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  assigned_worker_id uuid not null,
  category text not null,
  field text not null,
  priority public.task_priority not null default 'medium',
  status public.task_status not null default 'pending',
  schedule_start timestamptz not null,
  estimated_duration_minutes integer not null default 60,
  description text,
  created_by uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tasks_assigned_worker_id_fkey foreign key (assigned_worker_id)
    references public.profiles (id) on delete restrict,
  constraint tasks_category_length check (char_length(trim(category)) between 1 and 80),
  constraint tasks_field_length check (char_length(trim(field)) between 1 and 80),
  constraint tasks_duration_range check (estimated_duration_minutes between 15 and 1440),
  constraint tasks_description_length check (description is null or char_length(description) <= 2000)
);

create index if not exists tasks_schedule_idx on public.tasks (schedule_start);
create index if not exists tasks_status_idx on public.tasks (status);
create index if not exists tasks_worker_idx on public.tasks (assigned_worker_id);

create or replace function public.set_task_updated_at()
returns trigger language plpgsql set search_path = '' as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists tasks_set_updated_at on public.tasks;
create trigger tasks_set_updated_at before update on public.tasks
  for each row execute procedure public.set_task_updated_at();

alter table public.tasks enable row level security;
revoke all on table public.tasks from anon, authenticated;
grant all on table public.tasks to service_role;
grant usage on type public.task_priority to service_role;
grant usage on type public.task_status to service_role;
grant usage, select on sequence public.tasks_id_seq to service_role;
