-- Normalize task, schedule, and inventory configuration so managed values come
-- from database records instead of application source code.

create table if not exists public.task_categories (
  id bigint generated by default as identity primary key,
  category_name text not null,
  description text,
  status boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists task_categories_name_key
  on public.task_categories (lower(category_name));

create table if not exists public.task_priorities (
  id bigint generated by default as identity primary key,
  priority_name text not null,
  code text not null unique,
  status boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.task_statuses (
  id bigint generated by default as identity primary key,
  status_name text not null,
  code text not null unique,
  status boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.schedule_statuses (
  id bigint generated by default as identity primary key,
  status_name text not null,
  code text not null unique,
  status boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.farm_fields (
  id bigint generated by default as identity primary key,
  field_name text not null,
  description text,
  status boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists farm_fields_name_key on public.farm_fields (lower(field_name));

create table if not exists public.inventory_categories (
  id bigint generated by default as identity primary key,
  category_name text not null,
  code text not null unique,
  description text,
  status boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists inventory_categories_name_key
  on public.inventory_categories (lower(category_name));

create table if not exists public.measurement_units (
  id bigint generated by default as identity primary key,
  unit_name text not null,
  abbreviation text not null unique,
  status boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.pineapple_sizes (
  id bigint generated by default as identity primary key,
  size_name text not null unique,
  status boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.equipment_types (
  id bigint generated by default as identity primary key,
  type_name text not null unique,
  status boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.task_categories (category_name, description) values
  ('Planting', 'Planting and crop establishment activities'),
  ('Irrigation', 'Watering and irrigation activities'),
  ('Fertilization', 'Fertilizer application activities'),
  ('Crop Maintenance', 'Routine crop care and field maintenance'),
  ('Monitoring', 'Farm and crop monitoring activities'),
  ('Pest & Disease', 'Pest and disease prevention or treatment'),
  ('Harvesting', 'Crop harvesting activities'),
  ('Post-Harvest', 'Post-harvest handling activities'),
  ('Distribution', 'Produce distribution activities')
on conflict do nothing;

insert into public.task_priorities (priority_name, code, sort_order) values
  ('Low', 'low', 10), ('Medium', 'medium', 20), ('High', 'high', 30), ('Urgent', 'urgent', 40)
on conflict (code) do nothing;

insert into public.task_statuses (status_name, code, sort_order) values
  ('Pending', 'pending', 10), ('In Progress', 'in_progress', 20),
  ('Completed', 'completed', 30), ('Cancelled', 'cancelled', 40)
on conflict (code) do nothing;

insert into public.schedule_statuses (status_name, code, sort_order) values
  ('Scheduled', 'scheduled', 10), ('In Progress', 'in_progress', 20),
  ('Completed', 'completed', 30), ('Cancelled', 'cancelled', 40)
on conflict (code) do nothing;

insert into public.farm_fields (field_name) values
  ('Field A'), ('Field B'), ('Field C'), ('Field D')
on conflict do nothing;

insert into public.inventory_categories (category_name, code, description) values
  ('Pineapple', 'pineapple', 'Harvested pineapple inventory'),
  ('Fertilizer', 'fertilizer', 'Fertilizer and soil amendment inventory'),
  ('Pesticide', 'pesticide', 'Pest and disease control inventory'),
  ('Equipment', 'equipment', 'Farm tools and equipment inventory')
on conflict (code) do nothing;

insert into public.measurement_units (unit_name, abbreviation) values
  ('Pieces', 'pcs'), ('Kilograms', 'kg'), ('Bags', 'bags'),
  ('Liters', 'L'), ('Bottles', 'bottles'), ('Units', 'units')
on conflict (abbreviation) do nothing;

insert into public.pineapple_sizes (size_name) values ('Small'), ('Medium'), ('Large')
on conflict (size_name) do nothing;

insert into public.equipment_types (type_name) values
  ('Hand Tool'), ('Power Tool'), ('Vehicle'), ('Irrigation Equipment'), ('Safety Equipment')
on conflict (type_name) do nothing;

-- Preserve any existing custom values before replacing text columns with keys.
insert into public.task_categories (category_name)
select distinct trim(category) from public.tasks
where trim(category) <> ''
on conflict do nothing;

insert into public.farm_fields (field_name)
select distinct trim(field) from public.tasks
where trim(field) <> ''
on conflict do nothing;

alter table public.tasks add column if not exists task_name text;
alter table public.tasks add column if not exists category_id bigint references public.task_categories(id) on delete restrict;
alter table public.tasks add column if not exists field_id bigint references public.farm_fields(id) on delete restrict;
alter table public.tasks add column if not exists priority_id bigint references public.task_priorities(id) on delete restrict;
alter table public.tasks add column if not exists status_id bigint references public.task_statuses(id) on delete restrict;

update public.tasks t set
  task_name = coalesce(nullif(trim(t.description), ''), trim(t.category)),
  category_id = c.id,
  field_id = f.id,
  priority_id = p.id,
  status_id = s.id
from public.task_categories c, public.farm_fields f, public.task_priorities p, public.task_statuses s
where lower(c.category_name) = lower(trim(t.category))
  and lower(f.field_name) = lower(trim(t.field))
  and p.code = t.priority::text
  and s.code = t.status::text;

alter table public.tasks alter column task_name set not null;
alter table public.tasks alter column category_id set not null;
alter table public.tasks alter column field_id set not null;
alter table public.tasks alter column priority_id set not null;
alter table public.tasks alter column status_id set not null;

create table if not exists public.schedules (
  id bigint generated by default as identity primary key,
  task_id bigint not null references public.tasks(id) on delete cascade,
  schedule_date date not null,
  start_time time not null,
  end_time time not null,
  location text not null,
  status_id bigint not null references public.schedule_statuses(id) on delete restrict,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint schedules_time_order check (end_time > start_time),
  constraint schedules_notes_length check (notes is null or char_length(notes) <= 2000)
);
create unique index if not exists schedules_task_key on public.schedules(task_id);
create index if not exists schedules_date_idx on public.schedules(schedule_date, start_time);

insert into public.schedules (task_id, schedule_date, start_time, end_time, location, status_id, notes)
select t.id,
  (t.schedule_start at time zone 'Asia/Manila')::date,
  (t.schedule_start at time zone 'Asia/Manila')::time,
  case
    when ((t.schedule_start + make_interval(mins => t.estimated_duration_minutes)) at time zone 'Asia/Manila')::date
      > (t.schedule_start at time zone 'Asia/Manila')::date
    then time '24:00:00'
    else ((t.schedule_start + make_interval(mins => t.estimated_duration_minutes)) at time zone 'Asia/Manila')::time
  end,
  f.field_name,
  ss.id,
  t.description
from public.tasks t
join public.farm_fields f on f.id = t.field_id
join public.task_statuses ts on ts.id = t.status_id
join public.schedule_statuses ss on ss.code = case ts.code when 'pending' then 'scheduled' else ts.code end
on conflict (task_id) do nothing;

drop index if exists public.inventory_active_name_variant_key;
alter table public.inventory_items add column if not exists inventory_category_id bigint references public.inventory_categories(id) on delete restrict;
alter table public.inventory_items add column if not exists unit_id bigint references public.measurement_units(id) on delete restrict;

insert into public.inventory_categories (category_name, code)
select distinct trim(item_type), lower(regexp_replace(trim(item_type), '[^a-zA-Z0-9]+', '_', 'g'))
from public.inventory_items where trim(item_type) <> ''
on conflict do nothing;

update public.inventory_items i set
  inventory_category_id = c.id,
  unit_id = u.id
from public.inventory_categories c, public.measurement_units u
where lower(c.category_name) = lower(trim(i.item_type))
  and u.abbreviation = case c.code
    when 'fertilizer' then 'bags' when 'pesticide' then 'L'
    when 'equipment' then 'units' else 'pcs' end;

alter table public.inventory_items alter column inventory_category_id set not null;
alter table public.inventory_items alter column unit_id set not null;

create table if not exists public.pineapple_inventory (
  inventory_id bigint primary key references public.inventory_items(id) on delete cascade,
  size_id bigint references public.pineapple_sizes(id) on delete restrict,
  harvest_date date
);
create table if not exists public.fertilizer_inventory (
  inventory_id bigint primary key references public.inventory_items(id) on delete cascade,
  formulation text not null,
  expiration_date date
);
create table if not exists public.pesticide_inventory (
  inventory_id bigint primary key references public.inventory_items(id) on delete cascade,
  pesticide_type text not null,
  expiration_date date
);
create table if not exists public.equipment_inventory (
  inventory_id bigint primary key references public.inventory_items(id) on delete cascade,
  equipment_type_id bigint references public.equipment_types(id) on delete restrict,
  condition text not null default 'Good',
  availability text not null default 'Available',
  last_maintenance date
);

insert into public.pineapple_inventory (inventory_id, size_id)
select i.id, ps.id from public.inventory_items i
join public.inventory_categories c on c.id = i.inventory_category_id and c.code = 'pineapple'
left join public.pineapple_sizes ps on lower(ps.size_name) = lower(trim(i.variant))
on conflict (inventory_id) do nothing;
insert into public.fertilizer_inventory (inventory_id, formulation)
select i.id, trim(i.variant) from public.inventory_items i
join public.inventory_categories c on c.id = i.inventory_category_id and c.code = 'fertilizer'
on conflict (inventory_id) do nothing;
insert into public.pesticide_inventory (inventory_id, pesticide_type)
select i.id, trim(i.variant) from public.inventory_items i
join public.inventory_categories c on c.id = i.inventory_category_id and c.code = 'pesticide'
on conflict (inventory_id) do nothing;
insert into public.equipment_inventory (inventory_id, condition)
select i.id, coalesce(nullif(trim(i.variant), ''), 'Good') from public.inventory_items i
join public.inventory_categories c on c.id = i.inventory_category_id and c.code = 'equipment'
on conflict (inventory_id) do nothing;

alter table public.inventory_items rename column stock_quantity to quantity;

drop trigger if exists schedules_set_updated_at on public.schedules;
create trigger schedules_set_updated_at before update on public.schedules
  for each row execute procedure public.set_task_updated_at();

create or replace function public.set_lookup_updated_at()
returns trigger language plpgsql set search_path = '' as $$
begin new.updated_at = now(); return new; end;
$$;

do $$
declare table_name text;
begin
  foreach table_name in array array[
    'task_categories','task_priorities','task_statuses','schedule_statuses','farm_fields',
    'inventory_categories','measurement_units','pineapple_sizes','equipment_types'
  ] loop
    execute format('drop trigger if exists %I on public.%I', table_name || '_set_updated_at', table_name);
    execute format('create trigger %I before update on public.%I for each row execute procedure public.set_lookup_updated_at()', table_name || '_set_updated_at', table_name);
  end loop;
end $$;

create unique index if not exists inventory_active_name_category_key
  on public.inventory_items (lower(item_name), inventory_category_id)
  where archived_at is null;

create or replace function public.add_inventory_stock(p_item_id bigint, p_quantity integer)
returns setof public.inventory_items language plpgsql security definer set search_path = '' as $$
begin
  if p_quantity is null or p_quantity <= 0 then raise exception 'Stock quantity must be greater than zero'; end if;
  return query update public.inventory_items set quantity = quantity + p_quantity
    where id = p_item_id and archived_at is null returning *;
  if not found then raise exception 'Inventory item not found'; end if;
end;
$$;

alter table public.tasks drop column if exists category;
alter table public.tasks drop column if exists field;
alter table public.tasks drop column if exists priority;
alter table public.tasks drop column if exists status;
alter table public.tasks drop column if exists schedule_start;
alter table public.inventory_items drop column if exists item_type;
alter table public.inventory_items drop column if exists variant;

alter table public.schedules enable row level security;
alter table public.task_categories enable row level security;
alter table public.task_priorities enable row level security;
alter table public.task_statuses enable row level security;
alter table public.schedule_statuses enable row level security;
alter table public.farm_fields enable row level security;
alter table public.inventory_categories enable row level security;
alter table public.measurement_units enable row level security;
alter table public.pineapple_sizes enable row level security;
alter table public.equipment_types enable row level security;
alter table public.pineapple_inventory enable row level security;
alter table public.fertilizer_inventory enable row level security;
alter table public.pesticide_inventory enable row level security;
alter table public.equipment_inventory enable row level security;

grant all on table public.schedules, public.task_categories, public.task_priorities,
  public.task_statuses, public.schedule_statuses, public.farm_fields,
  public.inventory_categories, public.measurement_units, public.pineapple_sizes,
  public.equipment_types, public.pineapple_inventory, public.fertilizer_inventory,
  public.pesticide_inventory, public.equipment_inventory to service_role;
grant usage, select on all sequences in schema public to service_role;

notify pgrst, 'reload schema';
