-- Buyer orders and atomic pineapple inventory allocation.
create table if not exists public.buyer_orders (
  id bigint generated by default as identity primary key,
  order_number text unique,
  buyer_id uuid not null references public.profiles(id) on delete restrict,
  delivery_method text not null check (delivery_method in ('delivery', 'pickup')),
  payment_method text not null check (payment_method in ('cash', 'bank', 'gcash')),
  payment_status text not null default 'unpaid' check (payment_status in ('unpaid', 'pending', 'paid', 'failed', 'refunded')),
  order_status text not null default 'pending' check (order_status in ('pending', 'confirmed', 'preparing', 'out_for_delivery', 'delivered', 'cancelled')),
  subtotal numeric(12, 2) not null check (subtotal >= 0),
  shipping_fee numeric(12, 2) not null default 0 check (shipping_fee >= 0),
  total_amount numeric(12, 2) not null check (total_amount >= 0),
  customer_note text,
  delivery_full_name text not null,
  delivery_mobile_number text,
  delivery_country text,
  delivery_region text,
  delivery_province text,
  delivery_city_municipality text,
  delivery_barangay text,
  estimated_delivery_at timestamptz not null default (now() + interval '2 days'),
  confirmed_at timestamptz,
  preparing_at timestamptz,
  out_for_delivery_at timestamptz,
  delivered_at timestamptz,
  cancelled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint buyer_orders_note_length check (customer_note is null or char_length(customer_note) <= 1000)
);

create table if not exists public.buyer_order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.buyer_orders(id) on delete cascade,
  pineapple_size_id bigint not null references public.pineapple_sizes(id) on delete restrict,
  product_name text not null,
  weight_label text not null,
  quantity integer not null check (quantity > 0),
  unit_price numeric(10, 2) not null check (unit_price >= 0),
  line_total numeric(12, 2) not null check (line_total >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.buyer_order_inventory_allocations (
  id bigint generated by default as identity primary key,
  order_item_id bigint not null references public.buyer_order_items(id) on delete cascade,
  inventory_item_id bigint not null references public.inventory_items(id) on delete restrict,
  quantity integer not null check (quantity > 0),
  created_at timestamptz not null default now()
);

create index if not exists buyer_orders_buyer_created_idx on public.buyer_orders(buyer_id, created_at desc);
create index if not exists buyer_orders_status_idx on public.buyer_orders(order_status, created_at desc);
create index if not exists buyer_order_items_order_idx on public.buyer_order_items(order_id);

create or replace function public.set_buyer_order_status_timestamps()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  if new.order_status is distinct from old.order_status then
    if new.order_status = 'confirmed' and new.confirmed_at is null then new.confirmed_at = now(); end if;
    if new.order_status = 'preparing' and new.preparing_at is null then new.preparing_at = now(); end if;
    if new.order_status = 'out_for_delivery' and new.out_for_delivery_at is null then new.out_for_delivery_at = now(); end if;
    if new.order_status = 'delivered' and new.delivered_at is null then new.delivered_at = now(); end if;
    if new.order_status = 'cancelled' and new.cancelled_at is null then new.cancelled_at = now(); end if;
  end if;
  return new;
end;
$$;

drop trigger if exists buyer_orders_set_status_timestamps on public.buyer_orders;
create trigger buyer_orders_set_status_timestamps
  before update on public.buyer_orders
  for each row execute procedure public.set_buyer_order_status_timestamps();

create or replace function public.place_buyer_order(
  p_buyer_id uuid,
  p_delivery_method text,
  p_payment_method text,
  p_customer_note text,
  p_items jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_profile public.profiles%rowtype;
  v_order_id bigint;
  v_order_number text;
  v_subtotal numeric(12, 2) := 0;
  v_shipping numeric(12, 2) := 0;
  v_item jsonb;
  v_size public.pineapple_sizes%rowtype;
  v_quantity integer;
  v_remaining integer;
  v_allocate integer;
  v_order_item_id bigint;
  v_inventory record;
begin
  if p_delivery_method not in ('delivery', 'pickup') then raise exception 'Invalid delivery method'; end if;
  if p_payment_method not in ('cash', 'bank', 'gcash') then raise exception 'Invalid payment method'; end if;
  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'The shopping cart is empty';
  end if;

  select * into v_profile from public.profiles where id = p_buyer_id;
  if not found or v_profile.role::text <> 'buyer' then raise exception 'Buyer profile not found'; end if;

  for v_item in select value from jsonb_array_elements(p_items)
  loop
    v_quantity := (v_item ->> 'quantity')::integer;
    if v_quantity is null or v_quantity <= 0 then raise exception 'Order quantities must be greater than zero'; end if;
    select * into v_size from public.pineapple_sizes
      where id = (v_item ->> 'product_id')::bigint and status = true and marketplace_enabled = true;
    if not found then raise exception 'A selected pineapple product is unavailable'; end if;
    v_subtotal := v_subtotal + (v_size.selling_price * v_quantity);
  end loop;

  if p_delivery_method = 'delivery' then v_shipping := 100.00; end if;

  insert into public.buyer_orders (
    buyer_id, delivery_method, payment_method, payment_status, subtotal, shipping_fee, total_amount,
    customer_note, delivery_full_name, delivery_mobile_number, delivery_country, delivery_region,
    delivery_province, delivery_city_municipality, delivery_barangay
  ) values (
    p_buyer_id, p_delivery_method, p_payment_method,
    case when p_payment_method = 'cash' then 'unpaid' else 'pending' end,
    v_subtotal, v_shipping, v_subtotal + v_shipping, nullif(trim(p_customer_note), ''),
    coalesce(nullif(trim(v_profile.full_name), ''), 'Buyer'), v_profile.mobile_number,
    v_profile.country, v_profile.region, v_profile.province, v_profile.city_municipality, v_profile.barangay
  ) returning id into v_order_id;

  v_order_number := 'JT-' || to_char(current_date, 'YYYYMMDD') || '-' || lpad(v_order_id::text, 6, '0');
  update public.buyer_orders set order_number = v_order_number where id = v_order_id;

  for v_item in select value from jsonb_array_elements(p_items)
  loop
    v_quantity := (v_item ->> 'quantity')::integer;
    select * into v_size from public.pineapple_sizes where id = (v_item ->> 'product_id')::bigint;

    insert into public.buyer_order_items (
      order_id, pineapple_size_id, product_name, weight_label, quantity, unit_price, line_total
    ) values (
      v_order_id, v_size.id, v_size.size_name || ' Pineapple', v_size.weight_label,
      v_quantity, v_size.selling_price, v_size.selling_price * v_quantity
    ) returning id into v_order_item_id;

    v_remaining := v_quantity;
    for v_inventory in
      select i.id, i.quantity
      from public.inventory_items i
      join public.inventory_categories c on c.id = i.inventory_category_id and c.code = 'pineapple'
      join public.pineapple_inventory pi on pi.inventory_id = i.id and pi.size_id = v_size.id
      where i.archived_at is null and i.quantity > 0
      order by pi.harvest_date asc nulls last, i.created_at asc
      for update of i
    loop
      exit when v_remaining = 0;
      v_allocate := least(v_remaining, v_inventory.quantity);
      update public.inventory_items set quantity = quantity - v_allocate where id = v_inventory.id;
      insert into public.buyer_order_inventory_allocations(order_item_id, inventory_item_id, quantity)
        values (v_order_item_id, v_inventory.id, v_allocate);
      v_remaining := v_remaining - v_allocate;
    end loop;

    if v_remaining > 0 then raise exception 'Insufficient stock for %', v_size.size_name || ' Pineapple'; end if;
  end loop;

  return jsonb_build_object(
    'id', v_order_id,
    'order_number', v_order_number,
    'subtotal', v_subtotal,
    'shipping_fee', v_shipping,
    'total_amount', v_subtotal + v_shipping,
    'order_status', 'pending'
  );
end;
$$;

alter table public.buyer_orders enable row level security;
alter table public.buyer_order_items enable row level security;
alter table public.buyer_order_inventory_allocations enable row level security;

revoke all on table public.buyer_orders, public.buyer_order_items, public.buyer_order_inventory_allocations from anon, authenticated;
revoke all on function public.place_buyer_order(uuid, text, text, text, jsonb) from public, anon, authenticated;
grant all on table public.buyer_orders, public.buyer_order_items, public.buyer_order_inventory_allocations to service_role;
grant usage, select on sequence public.buyer_orders_id_seq, public.buyer_order_items_id_seq, public.buyer_order_inventory_allocations_id_seq to service_role;
grant execute on function public.place_buyer_order(uuid, text, text, text, jsonb) to service_role;

notify pgrst, 'reload schema';
