-- Seller order workflow and permanent status audit history.
create table if not exists public.buyer_order_status_history (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.buyer_orders(id) on delete cascade,
  previous_status text,
  new_status text not null check (new_status in ('pending', 'confirmed', 'preparing', 'out_for_delivery', 'delivered', 'cancelled')),
  changed_by uuid references public.profiles(id) on delete set null,
  note text,
  created_at timestamptz not null default now(),
  constraint buyer_order_history_note_length check (note is null or char_length(note) <= 500)
);

create index if not exists buyer_order_status_history_order_idx
  on public.buyer_order_status_history(order_id, created_at desc);

create or replace function public.change_buyer_order_status(
  p_order_id bigint,
  p_new_status text,
  p_changed_by uuid,
  p_note text default null
)
returns public.buyer_orders
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_order public.buyer_orders%rowtype;
  v_worker public.profiles%rowtype;
  v_allocation record;
  v_previous_status text;
begin
  select * into v_worker from public.profiles where id = p_changed_by;
  if not found or v_worker.role::text <> 'farm_worker' or v_worker.worker_category::text <> 'seller' then
    raise exception 'Only seller accounts can manage orders';
  end if;

  select * into v_order from public.buyer_orders where id = p_order_id for update;
  if not found then raise exception 'Order not found'; end if;
  v_previous_status := v_order.order_status;
  if p_new_status not in ('confirmed', 'preparing', 'out_for_delivery', 'delivered', 'cancelled') then
    raise exception 'Invalid order status';
  end if;
  if v_order.order_status = p_new_status then return v_order; end if;

  if not (
    (v_order.order_status = 'pending' and p_new_status in ('confirmed', 'cancelled')) or
    (v_order.order_status = 'confirmed' and p_new_status in ('preparing', 'cancelled')) or
    (v_order.order_status = 'preparing' and p_new_status = 'out_for_delivery') or
    (v_order.order_status = 'out_for_delivery' and p_new_status = 'delivered')
  ) then
    raise exception 'Order cannot move from % to %', v_order.order_status, p_new_status;
  end if;

  if p_new_status = 'cancelled' then
    for v_allocation in
      select a.inventory_item_id, sum(a.quantity)::integer as quantity
      from public.buyer_order_inventory_allocations a
      join public.buyer_order_items oi on oi.id = a.order_item_id
      where oi.order_id = p_order_id
      group by a.inventory_item_id
    loop
      update public.inventory_items
      set quantity = quantity + v_allocation.quantity
      where id = v_allocation.inventory_item_id;
    end loop;
  end if;

  update public.buyer_orders
  set order_status = p_new_status
  where id = p_order_id
  returning * into v_order;

  insert into public.buyer_order_status_history (
    order_id, previous_status, new_status, changed_by, note
  ) values (
    p_order_id, v_previous_status,
    p_new_status, p_changed_by, nullif(trim(p_note), '')
  );

  return v_order;
end;
$$;

alter table public.buyer_order_status_history enable row level security;
revoke all on table public.buyer_order_status_history from anon, authenticated;
revoke all on function public.change_buyer_order_status(bigint, text, uuid, text) from public, anon, authenticated;
grant all on table public.buyer_order_status_history to service_role;
grant usage, select on sequence public.buyer_order_status_history_id_seq to service_role;
grant execute on function public.change_buyer_order_status(bigint, text, uuid, text) to service_role;

notify pgrst, 'reload schema';
