-- Permanent stock ledger for admin additions, buyer order deductions, and returns.
create table if not exists public.inventory_stock_movements (
  id bigint generated by default as identity primary key,
  inventory_item_id bigint not null references public.inventory_items(id) on delete restrict,
  movement_type text not null check (movement_type in ('stock_in', 'stock_out')),
  quantity integer not null check (quantity > 0),
  quantity_before integer not null check (quantity_before >= 0),
  quantity_after integer not null check (quantity_after >= 0),
  created_at timestamptz not null default now()
);

create index if not exists inventory_stock_movements_item_date_idx
  on public.inventory_stock_movements(inventory_item_id, created_at desc);

create or replace function public.record_inventory_stock_movement()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  if new.quantity is distinct from old.quantity then
    insert into public.inventory_stock_movements (
      inventory_item_id, movement_type, quantity, quantity_before, quantity_after
    ) values (
      new.id,
      case when new.quantity > old.quantity then 'stock_in' else 'stock_out' end,
      abs(new.quantity - old.quantity), old.quantity, new.quantity
    );
  end if;
  return new;
end;
$$;

drop trigger if exists inventory_record_stock_movement on public.inventory_items;
create trigger inventory_record_stock_movement
  after update of quantity on public.inventory_items
  for each row execute procedure public.record_inventory_stock_movement();

alter table public.inventory_stock_movements enable row level security;
revoke all on table public.inventory_stock_movements from anon, authenticated;
grant all on table public.inventory_stock_movements to service_role;
grant usage, select on sequence public.inventory_stock_movements_id_seq to service_role;

notify pgrst, 'reload schema';
