-- Vehicles and driver-owned delivery acceptance workflow.
create table if not exists public.delivery_vehicles (
  id bigint generated by default as identity primary key,
  vehicle_name text not null,
  plate_number text not null unique,
  status text not null default 'available' check (status in ('available', 'in_use', 'maintenance', 'inactive')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.buyer_orders
  add column if not exists assigned_vehicle_id bigint references public.delivery_vehicles(id) on delete set null,
  add column if not exists delivery_assignment_status text not null default 'assigned' check (delivery_assignment_status in ('assigned', 'accepted', 'picked_up', 'out_for_delivery', 'delivered', 'declined', 'failed')),
  add column if not exists delivery_accepted_at timestamptz,
  add column if not exists delivery_picked_up_at timestamptz;

create index if not exists buyer_orders_delivery_vehicle_idx
  on public.buyer_orders (assigned_vehicle_id)
  where assigned_vehicle_id is not null;

alter table public.delivery_vehicles enable row level security;
revoke all on table public.delivery_vehicles from anon, authenticated;
grant all on table public.delivery_vehicles to service_role;
grant usage, select on sequence public.delivery_vehicles_id_seq to service_role;

create or replace function public.set_delivery_vehicle_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists delivery_vehicles_updated_at on public.delivery_vehicles;
create trigger delivery_vehicles_updated_at before update on public.delivery_vehicles
for each row execute procedure public.set_delivery_vehicle_updated_at();

notify pgrst, 'reload schema';
